- database/src/main/kotlin/no/nav/su/se/bakover/database/DatabaseRepo.kt
Hittade en liten typo när jag gick igenom koden lite 😊.
> fix small typo

- .github/workflows/branch.yml
- client/src/main/kotlin/no/nav/su/se/bakover/client/person/PdlClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/person/PersonOppslagStub.kt
- client/src/main/resources/hentPerson.graphql
- client/src/main/resources/pdl.graphqls
- client/src/test/kotlin/no/nav/su/se/bakover/client/WiremockBase.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/azure/AzureClientTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/dokarkiv/DokArkivClientTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/inntekt/InntektClientTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveClientTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/pdf/PdfClientTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/person/PdlClientTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/sts/StsClientTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Fnr.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Person.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Telefonnummer.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/VedtakInnhold.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/PersonRoutes.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/PersonRoutesKtTest.kt
> Fetch more PDL fields and expose them as json

- client/src/main/kotlin/no/nav/su/se/bakover/client/dokarkiv/DokArkiv.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/dokarkiv/DokArkivClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/pdf/PdfClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/dokarkiv/DokArkivStub.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/dokarkiv/DokArkivClientTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Behandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Fnr.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnholdTestdataBuilder.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/VedtakInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregning.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadInnholdJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRouteMediator.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutes.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/CallContextTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadJsonTest.kt
Hovedsaklig en fix for å få søknadsinnsending til å fungere igjen, men det ligger også med den første versjonen av innvilgelsesbrev.
> Fiks søknadsinnsending + vedtaksbrev

- .github/workflows/branch.yml
- client/src/main/kotlin/no/nav/su/se/bakover/client/HttpClientBuilder.kt
> Fix oppgave

- client/src/main/kotlin/no/nav/su/se/bakover/client/dokarkiv/DokArkiv.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/dokarkiv/DokArkivClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/person/PersonFactory.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/dokarkiv/DokArkivStub.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/dokarkiv/DokArkivClientTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRouteMediator.kt
Vi hørte du ikke likte at vi bruker pdlData. Hva synes du om denne?
Co-authored-by: Ingar Almklov <ingar.almklov@nav.no>
Co-authored-by: Christian Mosveen <christian.mosveen@nav.no>
Co-authored-by: Aryan Iranzamini <aryan.iranzamini@nav.no>
> Using personFactory instead of pdfData for Person

- web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/SuMetrics.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/NaisRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutes.kt
Added class `SuMetrics` to easier handle metric related operations
Co-authored-by: Ramzi Abu Qassim <ramzi.abu.qassim@nav.no>
Co-authored-by: Ingar Almklov <ingar.almklov@nav.no>
Co-authored-by: Christian Mosveen <christian.mosveen@nav.no>
> Add custom metric for søknad

- client/src/main/kotlin/no/nav/su/se/bakover/client/oppdrag/simulering/SimuleringRequestBuilder.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/simulering/SimuleringRequestBuilderTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/simulering/SimuleringRequestBuilderValidationTest.kt
- client/src/test/resources/simulering/beregningSkjema.xsd
- client/src/test/resources/simulering/infomelding.xsd
- client/src/test/resources/simulering/oppdragSkjema.xsd
- client/src/test/resources/simulering/simpleTypes.xsd
- client/src/test/resources/simulering/simulerFpServiceServiceTypes.xsd
- client/src/test/resources/simulering/statusmelding.xsd
TODO : Finn en universal måte å håndtere UUID mot oppdragsSystemet (maks 30 tegn)
Co-authored-by: John Andre Hestad <john.andre.hestad@nav.no>
> Lagt til validering av soap melding og korrigert feilene

- database/src/main/kotlin/no/nav/su/se/bakover/database/DatabaseRepo.kt
- database/src/test/kotlin/no/nav/su/se/bakover/database/DatabaseRepoTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Behandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Sak.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/Oppdrag.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppgave/OppgaveConfig.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/BehandlingTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/PersistentDomainObjectTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/SakTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutes.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutesKtTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/sak/SakJsonTest.kt
Create oppdrag at the same time as sak is created.
Co-authored-by: Richard Martinsen <richard.martinsen@nav.no>
Co-authored-by: John Andre Hestad <john.andre.hestad@nav.no>
> Move Simulering from sak to Behandling.

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Grunnbeløp.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/VedtakInnhold.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/brev/BrevService.kt
Co-authored-by: Ramzi Abu Qassim <ramzi.abu.qassim@nav.no>
> Send value of G when generating avslags-pdf

- database/src/main/kotlin/no/nav/su/se/bakover/database/DatabaseRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/ObjectRepo.kt
- database/src/main/resources/db/migration/V14__mndberegning_fradrag_delete_cascade.sql
- database/src/test/kotlin/no/nav/su/se/bakover/database/DatabaseRepoTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Behandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/VedtakInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregning.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Fradrag.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/brev/BrevService.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingJsonTest.kt
Delete previously created beregninger, mndberegninger and fradrag when new ones are created for same behandling.
> Make bereging for behandling singular.

- client/src/main/kotlin/no/nav/su/se/bakover/client/ClientsBuilder.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/Extensions.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/ProdClientsBuilder.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/StubClientsBuilder.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/person/AdGraphApiClient.kt
- common/src/main/kotlin/no/nav/su/se/bakover/common/Extensions.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/TestClientsBuilder.kt
Used for example for getting the logged in user's NAVIdent
> Add AdGraphApiClient

- client/src/main/kotlin/no/nav/su/se/bakover/client/oppdrag/avstemming/AvstemmingDataBuilder.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/oppdrag/utbetaling/UtbetalingMqPublisher.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/oppdrag/utbetaling/UtbetalingRequestMapper.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/oppdrag/UtbetalingStub.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/avstemming/AvstemmingDataBuilderTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/utbetaling/UtbetalingPublisherTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/utbetaling/UtbetalingRequestTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/utbetaling/UtbetalingXmlMappingTest.kt
- common/src/main/kotlin/no/nav/su/se/bakover/common/Utils.kt
- common/src/test/kotlin/no/nav/su/se/bakover/common/UtilsKtTest.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/DatabaseRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/ObjectRepo.kt
- database/src/main/resources/db/migration/V22__oppdragsmelding_tidspunkt.sql
- database/src/test/kotlin/no/nav/su/se/bakover/database/DatabaseRepoTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Behandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/Oppdragsmelding.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/avstemming/Avstemmingsnøkkel.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/utbetaling/UtbetalingPublisher.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/BehandlingTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/avstemming/AvstemmingsnøkkelTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/avstemming/AvstemmingBuilder.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/avstemming/AvstemmingBuilderTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutesKtTest.kt
This allows oppdrag to retrieve all keys in a given time-interval to perform avstemming.
> Use avstemmingsnøkkel that is sortable by time.

- database/src/main/resources/db/migration/V27__Formue_status_refactor.sql
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandlingsinformasjon.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/BehandlingsinformasjonTestdataBuilder.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/BehandlingTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingJsonTest.kt
Refaktorerade Formue i `Behandlingsinformasjon`
* Ändrade navn från `OK` -> `VilkårOppfylt`
* Lade till Avslag status
> Refactor status for Formue & add avslag status

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Behandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/VedtakInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/VedtakInnholdTestdataBuilder.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregning.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/brev/BrevService.kt
Har delat upp Vedtaksinnhold i två typer; `Innvilgelsesvedtak` & `Avslagsvedtak`
Detta är gjort för att enklare skilja på de, och datan de trenger.
> Split VedtakInnhold into two types; avslag & innvilgelse

- database/src/main/resources/db/migration/V28__sats_ordinær.sql
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandlingsinformasjon.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Sats.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/GrunnbeløpTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/MånedsberegningTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutesKtTest.kt
Tydligen så heter det ordinær sats och ikke lav sats. 
Har refaktorert så att vi använder riktigt begrepp i koden.
> Sats refactor

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/Oppdrag.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/Utbetalingslinje.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/UtbetalingslinjeTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/utbetaling/OppdragGjenopptaStrategyTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/utbetaling/OppdragNyStrategyTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/utbetaling/OppdragStansStrategyTest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/behandling/BehandlingServiceImpl.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/utbetaling/StansUtbetalingService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/utbetaling/StartUtbetalingerService.kt
Moving scattered implementation from services to containing object Oppdrag.
> Implement different types of utbetalinger as separate strategies.

- common/src/main/kotlin/no/nav/su/se/bakover/common/Config.kt
- nais-dev.json
- nais-prod.json
- web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Authentication.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/AuthenticationTest.kt
Will redirect back to frontend (/logout/complete) on success.
Frontend should there handle it and remove tokens etc.
> Add endpoint for proper SSO logout

- web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Extensions.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/features/Authorization.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/sak/SakRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/utbetaling/stans/StansUtbetalingRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/utbetaling/start/StartUtbetalingRoutes.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutesKtTest.kt
This can be used by wrapping routes in `authorize(x)` where `x` is a list of
`Brukerrolle` which the user needs to be able to access that endpoint
> Add authorization feature

- database/src/main/resources/db/migration/V32__ektefelle_partner_samboer.sql
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnholdTestdataBuilder.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadInnholdJson.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadJsonTest.kt
Ändrat typen på information om ektefellen i søknaden.
> refactored ektefelle into multiple subtypes

- client/src/main/kotlin/no/nav/su/se/bakover/client/dokarkiv/DokArkiv.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/dokarkiv/DokArkivClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/dokdistfordeling/DokDistFordeling.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/dokdistfordeling/DokDistFordelingClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveHttpClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveResponse.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/dokarkiv/DokArkivStub.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/dokdistfordeling/DokDistFordelingStub.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/oppgave/OppgaveClientStub.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/dokarkiv/DokArkivClientTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/dokdistfordeling/DokDistFordelingClientTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveHttpClientTest.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/søknad/SøknadPostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/søknad/SøknadRepo.kt
- database/src/main/resources/db/migration/V36__søknad_journalId_oppgaveId.sql
- database/src/test/kotlin/no/nav/su/se/bakover/database/søknad/SøknadPostgresRepoTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/journal/JournalpostId.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppgave/OppgaveClient.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppgave/OppgaveConfig.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppgave/OppgaveId.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/behandling/BehandlingServiceImpl.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/brev/BrevService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/SøknadServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/NySøknadTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/SøknadServiceImplTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutesKtTest.kt
https://trello.com/c/JEj5dMyb
Kommer fler PRs på å ta det i bruk.
> Lagre oppgaveId og journalpostId på søknad

- database/src/main/resources/db/migration/V37_personlig_oppmøte.sql
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Behandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandlingsinformasjon.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/behandling/BehandlingsinformasjonTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutes.kt
Refaktorerte samtidlig litt i Behandlingsinformasjon for å la hvert vilkår avgjøre om det er oppfylt eller ei, og slik at det kan si sin egen avslagsgrunn.
> Update choices for personlig oppmøte

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnholdTestdataBuilder.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadInnholdJson.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadJsonTest.kt
I søknaden så skal vi inte längre fråga om:
- Det er mindre enn tre måneder til den utgår
- Man har søkt om forlengelse
(I oppholdstillatelse)
> Remove questions in søknad about oppholdstillatelse duration

- client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/person/PersonOppslagStub.kt
- common/src/test/kotlin/no/nav/su/se/bakover/common/TidspunktTest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/SøknadService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/SøknadServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/NySøknadTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutes.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/PersonRoutesKtTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutesKtTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadJsonTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutesKtTest.kt
Lagd till en endepunkt som returnerer pdf:en till søknaden.
För att enkelt kunna kalla på det endepunktet så returnerar vi søknaden etter det har blivit sendt inn.
> Søknadsutskrift

- database/src/main/resources/db/migration/V44__rename_fra_to_valuta_trygdeYtelserIUtlandet.sql
Slik at vi kan begynne å bruke "valuta" i stedet for "fra".
> Reset all TrygdeytelseIUtlandet data

- client/src/main/kotlin/no/nav/su/se/bakover/client/dokdistfordeling/DokDistFordeling.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/dokdistfordeling/DokDistFordelingClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/dokdistfordeling/DokDistFordelingStub.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/dokdistfordeling/DokDistFordelingClientTest.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/behandling/BehandlingPostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/behandling/BehandlingRepo.kt
- database/src/main/resources/db/migration/V45__behandling_journalpostId_og_brev.sql
- database/src/test/kotlin/no/nav/su/se/bakover/database/behandling/BehandlingPostgresRepoTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/BehandlingFactory.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/BehandlingMetrics.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/BrevbestillingId.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/behandling/BehandlingService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/behandling/BehandlingServiceImpl.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/brev/BrevService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/brev/BrevServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/behandling/BehandlingServiceImplTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/behandling/UnderkjennBehandlingTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/brev/BrevServiceImplTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/lukk/LukkSøknadServiceImplTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/metrics/BehandlingMicrometerMetrics.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutes.kt
Refaktorert rekkefølgen og lagt på fler metrikker
> Persister journalpostId og BrevbestillingId ved iverksetting

- database/src/main/kotlin/no/nav/su/se/bakover/database/søknad/SøknadPostgresRepo.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnholdTestdataBuilder.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadInnholdJson.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadJsonTest.kt
Har fixat så att vi nu lagrer adressen till brukeren från søknaden.
> Save søkers chosen address in søknad

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandling.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/BehandlingTest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/behandling/BehandlingService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/behandling/BehandlingServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/behandling/BehandlingBeregningTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/behandling/BehandlingTestUtils.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutes.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutesKtTest.kt
La til full testdekning for service-funksjonen. TODO til senere er å rydde opp i web-laget
> Attestant kan ikke godkjenne sin egen beregning

- client/src/main/kotlin/no/nav/su/se/bakover/client/oppdrag/OppdragDefaults.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveHttpClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveResponse.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveHttpClientTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutes.kt
> Beskrivelse må ta vare på eksisterende beskrivelse til slutt

- .github/workflows/branch.yml
- .github/workflows/master.yml
- Dockerfile
- build.gradle.kts
- common/src/test/kotlin/no/nav/su/se/bakover/common/TidspunktTest.kt
Hvis vi gjør dette, må folk endre java-versjonene sine lokalt. Anbefaler sdkman.
```
sdk install java 15.0.1-open
sdk use java 15.0.1-open
```
I tillegg må man endre IntelliJ sine module settings til å bruke Java 15 en 4-5 plasser ;)
> Bump java from 12 to 15

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandling.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/BehandlingTest.kt
-Bug was causing forventet inntekt (yearly sum) to be distributed evenly across the beregningsperiode. This caused shorter periods (x < 12) to have to high fradrag, and longer periods (x > 12) to low fradrag.
-Fix by identifying the monthly sum from the behandlingsinformasjon (yearly sum), and multiply the monthly sum by the amount of months to be calculated.
> Fix bug with regards to how we calculate fradrag for forventet inntekt.

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnhold.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/BoforholdTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknad/SøknadPdfInnholdJsonTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadInnholdJson.kt
Vi manglet bruksenhetsnummer på adresser tidigare. Denna PR:en har lagt in stötte för det.
> Correctly format addresses in søknad pdf

- client/src/main/kotlin/no/nav/su/se/bakover/client/dokarkiv/Journalpost.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveHttpClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/person/PdlClient.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/dokarkiv/DokArkivClientTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/dokarkiv/JournalpostFactoryTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Kodeverk.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppgave/OppgaveConfig.kt
-Extract common "kodeverk" to separate file.
Co-authored-by: Aryan Iranzamini <aryaniranzamini@gmail.com>
> Endre behandlingstema ved journalføring til ab0431 (SU - Ufør flykning)

- README.md
- client/src/main/kotlin/no/nav/su/se/bakover/client/StubClientsBuilder.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/azure/AzureClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/azure/OAuth.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/azure/AzureClientStub.kt
- common/src/main/kotlin/no/nav/su/se/bakover/common/Config.kt
- common/src/test/kotlin/no/nav/su/se/bakover/common/ApplicationConfigTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/AuthenticationConfig.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Extensions.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/me/MeRoutes.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/AuthenticationTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/TestEnvironment.kt
Denne avhenger av https://github.com/navikt/su-se-framover/pull/561.
> Fjern autentiseringskode, godta kun on-behalf-of tokens i stedet

- common/src/main/kotlin/no/nav/su/se/bakover/common/Config.kt
- common/src/test/kotlin/no/nav/su/se/bakover/common/ApplicationConfigTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/AuthenticationConfig.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Extensions.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/AuthenticationTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/TestEnvironment.kt
> isRunningLocal kan ha 3 verdier (local, test, nais)

- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/ErrorJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Resultat.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/RevurderingRoutes.kt
Jeg foreslår å gjøre det så enkelt til å begynne med. Dersom teamet synes det er ok, splitter jeg litt opp i fler route-filer og lager fler route-tester.
> Legg til feilkoder på revurderingsendepunktene

- database/src/main/kotlin/no/nav/su/se/bakover/database/vedtak/snapshot/VedtakssnapshotJson.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandlingsinformasjon.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/BeregningStrategy.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/LagBrevRequest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/behandling/BehandlingsinformasjonTest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingsinformasjonJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/BeregnOgSimulerRevurderingRoute.kt
https://trello.com/c/vp8kVIYD
Vi har fremdeles en del potensielle bugs her (nullables), men det skal ikke lenger tryne når vi prøver utledeSats i json-laget.
> Ikke kast exceptions fra utledBeregningsstrategi

- database/src/main/kotlin/no/nav/su/se/bakover/database/revurdering/RevurderingPostgresRepo.kt
- database/src/main/resources/db/migration/V67__revurdering_add_fritekst.sql
- database/src/test/kotlin/no/nav/su/se/bakover/database/RevurderingPostgresRepoTest.kt
- database/src/test/kotlin/no/nav/su/se/bakover/database/TestDataHelper.kt
- database/src/test/kotlin/no/nav/su/se/bakover/database/vedtak/VedtakPosgresRepoTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/BrevInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/LagBrevRequest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/visitor/LagBrevRequestVisitor.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/visitor/FinnAttestantVisitorTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/visitor/LagBrevRequestVisitorTest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/OpprettRevurderingServiceTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImplTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/statistikk/RevurderingStatistikkMapperTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/statistikk/StatistikkServiceImplTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/BrevutkastForRevurderingRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/SendRevurderingTilAttestering.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/BeregnOgSimulerRevurderingRouteKtTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/IverksettRevurderingRouteKtTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OppdaterRevurderingsperiodeRouteKtTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OpprettRevurderingRouteKtTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/RevurderingJsonTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/SendRevurderingTilAttesteringRouteKtTest.kt
Dette er ikke den beste måten å løse det på, og heller ikke sånn vi vil ha det. Samtidig så er det en feature vi må ha på plass kjapt, så dette kan sees på som en snarvei som vi må fikse opp i etter hvert.
> Få med fritekst i brev for revurdering

- web/src/main/kotlin/no/nav/su/se/bakover/web/Extensions.kt
https://github.com/navikt/naudit
> Slå av audit-logging inntil vi har på plass naudit

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/VurderOmBeregningHarEndringerIYtelse.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/VurderOmBeregningHarEndringerIYtelseTest.kt
Co-authored-by: Jacob Meidell <jacob.meidell@nav.no>
> Assess if there has been a change in beregning's ytelse

- client/src/main/kotlin/no/nav/su/se/bakover/client/UnleashBuilder.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/ToggleRoutes.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/TestEnvironment.kt
-Unngå exceptions ved kjøring av test/lokalt
-Eksplisitt sett FakeUnleash som default for testSusebakover()
> Ekstraher oppsett for unleash i egen builder.

- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/FradragJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/UtenlandskInntektJson.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutesKtTest.kt
> Fiks bug hvor alle fradrag ble brukers fradrag

- database/src/main/kotlin/no/nav/su/se/bakover/database/DatabaseEx.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/avstemming/AvstemmingPostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/grunnlag/UføregrunnlagPostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/grunnlag/VilkårsvurderingPostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/hendelseslogg/HendelsesloggPostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/revurdering/RevurderingPostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/søknad/SøknadPostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/søknadsbehandling/SøknadsbehandlingPostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/utbetaling/UtbetalingPostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/vedtak/VedtakPosgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/vedtak/snapshot/VedtakssnapshotPostgresRepo.kt
- database/src/test/kotlin/no/nav/su/se/bakover/database/DatabaseExKtTest.kt
- database/src/test/kotlin/no/nav/su/se/bakover/database/avstemming/AvstemmingPostgresRepoTest.kt
…sjekk på at update ikke kan kjøres uten where
> lag egen insert funksjon for å skille update og insert, og legge inn sjekk på at det ikke er lov å oppdatere uten where

- database/src/test/kotlin/no/nav/su/se/bakover/database/RevurderingPostgresRepoTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/OppdaterRevurderingServiceTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImplTest.kt
Co-authored-by: Jacob Meidell <jacob.meidell@nav.no>
> Resett grunnlag for revurdering når den oppdateres

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/VedtakInnholdTestdataBuilder.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/BrevInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/LagBrevRequest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/grunnlag/Grunnlagsdata.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/visitor/LagBrevRequestVisitor.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/AvslagsBrevInnholdTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/BrevInnholdTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/visitor/LagBrevRequestVisitorTest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImplTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/vedtak/FerdigstillVedtakServiceImplTest.kt
Co-authored-by: Aryan Iranzamini <aryan.iranzamini@nav.no>
Co-authored-by: Richard Martinsen <richard.martinsen@nav.no>
> vis tekst om IEU større enn 0

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnhold.kt
tilhørende PR: https://github.com/navikt/su-se-framover/pull/807
> erUførFlyktning kan nå være null hvis EPS er over 67 år

- client/src/main/kotlin/no/nav/su/se/bakover/client/person/PdlClient.kt
Vi fikk et par feilmeldinger fra PDL i produksjon, men vi logget ikke underforliggende årsak.
> Logg PDL feilmelding

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/VurderAvslagGrunnetBeregning.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/avslag/Avslagsgrunn.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/BrevInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/LagBrevRequest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/Vedtak.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/vilkår/Vilkår.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/visitor/LagBrevRequestVisitor.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/behandling/VurderAvslagGrunnetBeregningKtTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/AvslagsBrevInnholdTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/BrevInnholdTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/RevurderingTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/vilkår/VilkårsvurderingerTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/visitor/LagBrevRequestVisitorTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/grunnlag/UførevilkårJson.kt
tilhørende pdf-gen PR: https://github.com/navikt/su-pdfgen/pull/26
Vilkår som nå fører til opphør blir lagt til som en del av avslagsgrunner for opphørsvedtak.
> Opphørsgrunn for uføre vilkåret

- .github/workflows/branch-deploy.yml
Krever at origin/master sin HEAD er en ancestor
> Legg til guard ved deploy branch til dev-fss

- .github/workflows/branch-deploy.yml
- .github/workflows/branch.yml
- .github/workflows/master.yml
- Dockerfile
- build.gradle.kts
Testet i preprod og testet revurdere.
Viser seg at vi har en generell bug med connection error mot postgres: https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-test-001469?id=ANMngXkBXzKERMfPIgt8
Lager egne tasks og PR på det før vi merger denne.
> Bytt fra Java 15 til 16

- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/drift/DriftRoutes.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/drift/FixIverksettingerTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/drift/FixSøknaderTest.kt
Fix endepunkt returnerer ok selv om listen inneholder noen som ikke kunne fikses
> Fix endepunkt returnerer 200 selv om noen rader ikke ble rettet

- build.gradle.kts
- common/src/main/kotlin/no/nav/su/se/bakover/common/JmsConfig.kt
> Bump versjon av MQ-klient

- web/src/main/kotlin/no/nav/su/se/bakover/web/Extensions.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Resultat.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/ToggleRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/person/PersonRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/FortsettEtterForhåndsvarselRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/Revurderingsfeilresponser.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/UnderkjennRevurdering.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/sak/SakRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/lukk/LukkSøknadErrorHandler.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/LeggTilGrunnlagBosituasjonRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/FradragJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/PeriodeJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/StønadsperiodeJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/UtenlandskInntektJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/utbetaling/stans/StansUtbetalingRoutes.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/ResultatTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/lukk/LukkSøknadErrorHandlerTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutesKtTest.kt
Og fjern varianten med bare feilmeldingsstreng.
> Bruk errorJson med feilmelding og kode på alle feil

- client/src/main/kotlin/no/nav/su/se/bakover/client/person/MicrosoftGraphApiClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/person/MicrosoftGraphApiClientStub.kt
- database/src/test/kotlin/no/nav/su/se/bakover/database/revurdering/RevurderingPostgresRepoTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/behandling/BehandlingTestUtils.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImplTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceMocks.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingTestUtils.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceBrevTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/vedtak/FerdigstillVedtakServiceImplTest.kt
- test-common/src/main/kotlin/BeregningTestData.kt
- test-common/src/main/kotlin/GenerelleTestData.kt
- test-common/src/main/kotlin/RevurderingTestData.kt
- test-common/src/main/kotlin/SøknadsbehandlingTestData.kt
- test-common/src/main/kotlin/UtbetalingTestData.kt
- test-common/src/main/kotlin/VedtakTestData.kt
Denne løser kun tredje punktet i https://trello.com/c/qJ3q1jkP/870-oppf%C3%B8lging-test-data-komponent, men jeg tenkte vi kunne dele det opp flere PRs.
> Rydd opp og bruk felles testdata i FerdigstillVedtakServiceImplTest

- client/src/main/kotlin/no/nav/su/se/bakover/client/person/PdlClient.kt
Ryddet litt duplisert kode og andre warnings i PdlClient.
> Rydd opp litt warnings i PdlClient

- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingService.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/person/PersonRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/BeregnOgSimulerRevurderingRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/BrevutkastForRevurderingRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/ForhåndsvarslingRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/FortsettEtterForhåndsvarselRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/HentGrunnlagRevurderingRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/IverksettRevurderingRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/LeggTilBosituasjonRevurderingRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/LeggTilFormueRevurderingRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/LeggTilFradragRevurderingRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/LeggTilUføreRevurderingRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OppdaterRevurderingsperiodeRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OpprettRevurderingRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/Revurderingsfeilresponser.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/SendRevurderingTilAttestering.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/UnderkjennRevurdering.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/lukk/LukkSøknadErrorHandler.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/LeggTilGrunnlagBosituasjonRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/LeggTilGrunnlagFradragRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/LeggTilGrunnlagUføreRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutes.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/BrevutkastForRevurderingRouteTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/LeggTilFormueRevurderingRouteKtTest.kt
Front: https://github.com/navikt/su-se-framover/pull/1096
> Fjern ubrukte feiltyper & slå sammen lignende feil

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/ServiceBuilder.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/statistikk/Statistikk.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/statistikk/StatistikkSchemaValidator.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/statistikk/StatistikkService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/statistikk/StatistikkServiceImpl.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/statistikk/StønadsstatistikkMapper.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
- service/src/main/resources/statistikk/stonad_schema.json
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImplTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/statistikk/StatistikkSchemaValidatorTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/statistikk/StatistikkServiceImplTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/statistikk/StønadsstatistikkMapperTest.kt
Publiserer events for stønadsstatistikk ved endring av ytelse (iverksatt behandling eller iverksatt/opphørt revurdering).
> Publiser hendelser til stønadsstatistikk

- common/src/main/kotlin/no/nav/su/se/bakover/common/Config.kt
- common/src/test/kotlin/no/nav/su/se/bakover/common/ApplicationConfigTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/personhendelser/PersonhendelseOppgaveJob.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/TestEnvironment.kt
Trenger raskare intervall i preprod for å enklere teste.
> Forskjell i intervall mellom prod og preprod for personhendelsejobb

- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/IverksettRevurderingRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OpprettRevurderingRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/Revurderingsfeilresponser.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/SendRevurderingTilAttestering.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/UnderkjennRevurdering.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutes.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutesKtTest.kt
siden du er her, så kan du se på https://github.com/navikt/su-se-framover/pull/1101 
:) :) :) :) :) :) :) :)
> bruk delt feilkoder

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/IdentifiserSaksbehandlingsutfallSomIkkeStøttes.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/VurderOpphørVedRevurdering.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/IdentifiserRevurderingsutfallSomIkkeStøttesTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/VurderOpphørVedRevurderingTest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/ServiceBuilder.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RegulerGrunnbeløpServiceImplTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingBeregnOgSimulerTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingLeggTilFormueServiceTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingLeggTilUføregrunnlagTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImplTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceMocks.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingTestUtils.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/BeregnOgSimulerRevurderingRoute.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/BeregnOgSimulerRevurderingRouteKtTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/LeggTilFormueRevurderingRouteKtTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/LeggTilFradragRevurderingRouteKtTest.kt
https://github.com/navikt/su-se-framover/pull/1115
> sender feil om at utfall ikke støttes for hvert steg til front-end

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandlingsinformasjon.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/behandling/BehandlingsinformasjonTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/behandling/BehandlingsinformasjonTestData.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/grunnlag/VilkårsvurderingService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
https://trello.com/c/WUxfMCHp/1006-refaktorering-av-behandlingsinformasjon-og-vilk%C3%A5rsvurderinger
> Behandlingsinformasjon vilkår bosituasjon formue fiks

- database/src/main/kotlin/no/nav/su/se/bakover/database/dokument/DokumentPostgresRepo.kt
- database/src/test/kotlin/no/nav/su/se/bakover/database/dokument/DokumentPostgresRepoTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/dokument/Dokument.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/vedtak/FerdigstillVedtakService.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/dokument/DokumentJson.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/dokument/DokumentJsonKtTest.kt
Ønsker å vise til saksbehandler at journalføring og brevsending er gjort
> Hente ut felter fra dokument_distribusjon for å vise status på brev

- README.md
- resetdb.sh
Docker har tatt inn compose under vingene sine som sin egen plugin.
Det kan hende man må oppdatere docker 🤷
> Bytt fra docker-compose til docker compose

- client/src/main/kotlin/no/nav/su/se/bakover/client/dokarkiv/Journalpost.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/dokarkiv/JournalpostFactory.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveHttpClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/oppgave/OppgaveClientStub.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Kodeverk.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/BrevInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/BrevTemplate.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/LagBrevRequest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/PdfTemplate.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppgave/OppgaveConfig.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/ServiceBuilder.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/Services.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/kontrollsamtale/KontrollsamtaleService.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/AccessCheckProxyTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/kontrollsamtale/KontrollsamtaleServiceImplTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/kontrollsamtale/KontrollsamtaleRoutes.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/TestServicesBuilder.kt
Sender et innkallingsbrev til bruker, samt lager en fremleggsoppgave i Gosys. Vi skal sannsynligvis ha mer på kontrollsamtaler etterhvert, så lagde egen route og service i stedet for å prøve å presse det inn et sted det bare ville delvis passet.
https://github.com/navikt/su-se-framover/pull/1340
> Kall inn til kontrollsamtale

- database/src/test/kotlin/no/nav/su/se/bakover/database/revurdering/LagreOgHentAvsluttetRevurderingTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/AvsluttetRevurderingTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/LeggTilUtenlandsoppholdTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/RevurderingTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/visitor/FinnAttestantVisitorTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/visitor/SkalSendeBrevVisitorTest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/brev/BrevServiceImplTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingBeregnOgSimulerTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingIngenEndringTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/StansAvYtelseServiceTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/statistikk/BehandlingStatistikkMapperTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/BeregnOgSimulerRevurderingRoute.kt
https://trello.com/c/5iblmYP9/1090-endre-sperre-for-10-endring-til-%C3%A5-v%C3%A6re-en-advarsel
https://github.com/navikt/su-se-framover/pull/1458
> Fjern 10 prosent sjekk

- build.gradle.kts
- database/src/main/kotlin/no/nav/su/se/bakover/database/DatabaseBuilder.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/revurdering/RevurderingPostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/vedtak/VedtakPostgresRepo.kt
- database/src/main/resources/db/migration/V123__legg_til_klage_i_vedtak.sql
- database/src/test/kotlin/no/nav/su/se/bakover/database/TestDataHelper.kt
- database/src/test/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepoTest.kt
- database/src/test/kotlin/no/nav/su/se/bakover/database/vedtak/LagreOgHentKlagevedtakTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/Klagevedtak.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/ServiceBuilder.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/klage/KlageServiceImpl.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/vedtak/VedtakService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/vedtak/VedtakServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/BekreftVilkårsvurdertKlageTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/BekreftVurdertKlageTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/IverksettAvvistKlageTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/KlageServiceMocks.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/OversendKlageTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/SendKlageTilAttesteringTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/VilkårsvurderKlageTest.kt
- web-regresjonstest/build.gradle.kts
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/vedtak/VedtakJson.kt
Merges sammen med: https://github.com/navikt/su-se-framover/pull/1475
> Legg til klagevedtak

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/kontrollsamtale/Kontrollsamtale.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/kontrollsamtale/KontrollsamtaleService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/kontrollsamtale/KontrollsamtaleServiceImplTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/kontrollsamtale/KontrollsamtaleRoutes.kt
Strengere sjekk for statusoverganger, samt verifiser at saken har en gjeldende stønadsperiode før man kan kalle inn kontrollsamtale
> strengere sjekk på statusoverganger for kontrollsamtale

- client/src/main/kotlin/no/nav/su/se/bakover/client/kabal/KabalRequest.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/klage/KlagePostgresRepo.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/Hjemler.kt
Ikke merge denne før Kabal har lagt til hjemlene først.
Merges sammen med https://github.com/navikt/su-se-framover/pull/1500
> Legg til klagehjemlene 11, 17 og 21

- service/src/main/kotlin/no/nav/su/se/bakover/service/ServiceBuilder.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingSendTilAttesteringTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceMocks.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingTestUtils.kt
Legg til feature-toggle for å kunne tillate opprettelse av feilkonto hos oppdrag. Et steg på veien for å komme i gang med tilbakekreving.
> Legg til feature-toggle for feilutbetalinger.

- client/src/main/kotlin/no/nav/su/se/bakover/client/journalpost/JournalpostClientStub.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/journalpost/JournalpostHttpClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/journalpost/JournalpostResponse.kt
- client/src/main/resources/hentJournalpost.graphql
- client/src/test/kotlin/no/nav/su/se/bakover/client/journalpost/JournalpostHttpClientTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/journalpost/JournalpostResponseTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/journalpost/FerdigstiltJournalpost.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/journalpost/JournalpostClient.kt
- test-common/src/main/kotlin/HenterJournalpostTestData.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/klage/KlageRoutes.kt
Lagt til journalposttype og sjekker at dem er utgående. 
Logger exceptions dersom noe feiler ved deserialisering
> Gjør felter i Journalpost-responsen nullable

- client/src/main/kotlin/no/nav/su/se/bakover/client/kafka/KafkaPublisherClient.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/kafka/KafkaPublisherClientTest.kt
- common/src/main/kotlin/no/nav/su/se/bakover/common/Config.kt
- common/src/main/kotlin/no/nav/su/se/bakover/common/Utils.kt
- common/src/test/kotlin/no/nav/su/se/bakover/common/ApplicationConfigTest.kt
- web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/SharedRegressionTestData.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/JobberOgConsumers.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/avstemming/GrensesnittsavstemingJob.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/avstemming/KonsistensavstemmingJob.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/dokument/DistribuerDokumentJob.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/klage/klageinstans/KlageinstanshendelseJob.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/kontrollsamtale/KontrollsamtaleinnkallingJob.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/personhendelser/PersonhendelseOppgaveJob.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/utbetaling/kvittering/LokalKvitteringJob.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/TestEnvironment.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/services/avstemming/KonsistensavstemmingJobTest.kt
Vi har opplevd at en del av jobbene går i beina på hverandre når det kommer til databaseconnections
> Kjør jobber med mellomrom

- common/src/main/kotlin/no/nav/su/se/bakover/common/persistence/SessionContext.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/PostgresSessionFactory.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/kontrollsamtale/KontrollsamtalePostgresRepo.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/kontrollsamtale/KontrollsamtaleRepo.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/ServiceBuilder.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/kontrollsamtale/KontrollsamtaleService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/kontrollsamtale/KontrollsamtaleServiceImplTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/IverksettRevurderingTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceIverksettTest.kt
- test-common/src/main/kotlin/DokumentTestData.kt
- test-common/src/main/kotlin/GenerelleTestData.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/JobberOgConsumers.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/kontrollsamtale/KontrollsamtaleRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/kontrollsamtale/KontrollsamtaleinnkallingJob.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/kontrollsamtale/KontrollsamtaleRoutesKtTest.kt
Har også ryddet litt opp i sessions for kontrollsamtale
> Endre kontrollsamtale fra left til right

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/kontrollsamtale/Kontrollsamtale.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/kontrollsamtale/KontrollsamtaleTest.kt
Frist ble ikke endret når ny dato for innkalling til kontrollsamtale ble satt
> Endring av dato på kontrollsamtale skal også endre fristen

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnholdTestdataBuilder.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknad/SøknadPdfInnholdJsonTest.kt
- web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/søknad/SøknadsinnholdJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadInnholdJson.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadJsonTest.kt
Henger sammen med https://github.com/navikt/su-se-framover/pull/1634 og https://github.com/navikt/su-pdfgen/pull/49
> Fjern sosialstønad fra søknadsdelene

- service/src/main/kotlin/no/nav/su/se/bakover/service/klage/KlageServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/SendKlageTilAttesteringTest.kt
Vi hadde konfig for attesteringsoppgave allerede, men den var ikke tatt i bruk.
> Sett riktig oppgavetype på attesteringsoppgavene for klage

- database/src/main/kotlin/no/nav/su/se/bakover/database/vedtak/VedtakPostgresRepo.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/regulering/ReguleringServiceImpl.kt
Endre sån att vi gjenbruker database session når vi henter regulering & forbedrer loggmeldingene så det blir enklere å følge med på.
> Regulering utbedringer

- client/src/main/kotlin/no/nav/su/se/bakover/client/oppgave/OppgavebeskrivelseMapper.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/oppgave/OppgavebeskrivelseMapperTest.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/personhendelse/PersonhendelsePostgresRepo.kt
- database/src/test/kotlin/no/nav/su/se/bakover/database/personhendelse/PersonhendelsePostgresRepoTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/personhendelse/Personhendelse.kt
- web/src/main/avro/Personhendelse.avdl
- web/src/main/avro/bostedsadresse/Bostedsadresse.avdl
- web/src/main/avro/common/adresse/Koordinater.avdl
- web/src/main/avro/common/adresse/Matrikkeladresse.avdl
- web/src/main/avro/common/adresse/PostadresseIFrittFormat.avdl
- web/src/main/avro/common/adresse/Postboksadresse.avdl
- web/src/main/avro/common/adresse/UkjentBosted.avdl
- web/src/main/avro/common/adresse/UtenlandskAdresse.avdl
- web/src/main/avro/common/adresse/UtenlandskAdresseIFrittFormat.avdl
- web/src/main/avro/common/adresse/Vegadresse.avdl
- web/src/main/avro/kontaktadresse/Kontaktadresse.avdl
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/personhendelser/PersonhendelseMapper.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/services/personhendelser/PersonhendelseConsumerTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/services/personhendelser/PersonhendelseMapperTest.kt
Per nå, så holder det å bare lagre at vi fikk inn en hendelse på endringen.
> Lytt på kontakt og bosteds-adresse endringer & lag gosys oppgaver

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Grunnbeløp.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/GrunnbeløpTest.kt
- web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/søknadsbehandling/grunnlagsdataOgVilkårsvurderinger/GrunnlagsdataOgVilkårsvurderinger.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/grunnlag/FormuevilkårJsonTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/RevurderingJsonTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingJsonTest.kt
Avventer med merge tills JAD har fått opp alla test cases
> Bumpe grunnbeløp for testing

- database/src/main/kotlin/no/nav/su/se/bakover/database/Session.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/beregning/BeregningMapper.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/grunnlag/FradragsgrunnlagPostgresRepo.kt
- database/src/main/resources/db/migration/V131__fradrag_annet.sql
- database/src/test/kotlin/no/nav/su/se/bakover/database/beregning/BeregningMapperTest.kt
- database/src/test/kotlin/no/nav/su/se/bakover/database/grunnlag/FradragsgrunnlagPostgresRepoTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/SlåSammenEkvivalenteMånedsberegningerTilBeregningsperioder.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/Fradrag.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/Fradragstype.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/beregning/FradragsMapper.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/FradragstypeTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/grunnlag/FradragsgrunnlagTest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingService.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/LeggTilGrunnlagFradragRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/FradragJson.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/grunnlag/FradragsgrunnlagJsonTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutesKtTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/BeregningJsonTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/FradragJsonTest.kt
En annen mulig variant @RamziAbuQassim @hestad - ikke helt finpusset kanskje, men ikke så langt ifra.
> Nye fradragstyper variant

- common/src/main/kotlin/no/nav/su/se/bakover/common/Utils.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/VedtakInnholdTestdataBuilder.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/BrevInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/LagBrevRequest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/Satsoversikt.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/beregning/Beregningsperiode.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/beregning/LagBrevinnholdForBeregning.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/visitor/LagBrevRequestVisitor.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/AvslagsBrevInnholdTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/BrevInnholdTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/SatsoversiktTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/beregning/LagBrevinnholdForBeregningTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/visitor/LagBrevRequestVisitorTest.kt
Se: https://github.com/navikt/su-pdfgen/pull/55
> Vis vurdering av bosituasjon/sats med tilhørende sats per periode i brev.

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Sak.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/GjeldendeVedtaksdata.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/vedtak/GjeldendeVedtaksdataTest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/GjenopptakAvYtelseService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/StansAvYtelseService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/sak/SakService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/sak/SakServiceImpl.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/sak/SakRoutes.kt
En annan tilnærming til tidligere PR som ble lukket:
https://github.com/navikt/su-se-bakover/pull/810
> Unngå utrygg bruk av perioden for gjelende vedtaksdata

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/grunnbeløp/GrunnbeløpFactory.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/satser/SatsFactoryForSupplerendeStønad.kt
-Fjern unødvendige override for hash/equals som tidligere ble brukt for caching med set.
> Cache basert på ikrafttredelsestidspunkt for endring.

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Søknadsinnhold.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadsinnholdJson.kt
Burde vi kanskje tenke på noe form for backend validering? Disse feltene er avhengig av oppholdstillatelse
> gjør felter i OppholdstillatelseAlder nullable

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/regulering/Regulering.kt
Fick en feil i prod där saksbehandler ikke kunne gå videre med manuell regulering p.g.a konsistensproblemer i gjeldendeVedtaksdata. Ønsker logging av hvilke problemer saksbehandler hade for å enklere feilsøke eller veilede.
> Legg til logging av hvilke konsistensproblemer bruker har for gitt sak

- nais-prod.json
Tror ikke det finnes en tilsvarende for utvikling.
> Bytt til HA-løsning for MQ i prod

- service/src/main/kotlin/no/nav/su/se/bakover/service/skatt/SkatteServiceImpl.kt
Passer også på at flere tråder ikke henter samme token samtidig.
> Mellomlagrer maskinportentoken fram til det utløper

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
Ser ut som vi må finne en ny måte å injecte env variables på:
>ApplicationConfigTest > environment variables() FAILED
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens
> Upgrade gradle to 7.5.1

- service/src/main/resources/statistikk/behandling_schema.json
- service/src/main/resources/statistikk/sak_schema.json
- service/src/main/resources/statistikk/stonad_schema.json
- service/src/main/resources/statistikk/verify_schemas_up_to_date.sh
Det er kun whitespace-endringer (og muligens en skrivefeil jeg rettet tidligere, men reverta nå) for å diffe raskere
La også inn et script for å sjekke det raskere.
> Oppdater statistikk skjemaer

- build.gradle.kts
Første steg av oppgradering. Tror 7.2.0 vil feile.
> Bump io.confluent:kafka-avro-serializer to 7.1.3

- database/src/test/kotlin/no/nav/su/se/bakover/database/revurdering/RevurderingPostgresRepoTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/Sak.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/GjeldendeVedtaksdata.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/OppdaterRevurderingServiceTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/OpprettRevurderingServiceTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OppdaterRevurderingsperiodeRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OpprettRevurderingRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/Revurderingsfeilresponser.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OppdaterRevurderingsperiodeRouteKtTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OpprettRevurderingRouteKtTest.kt
-Flytt funksjonalitet til sak og revurdering
-Bruk felles implementasjon for opprett/oppdater i større grad 
-Svar med feil dersom hele revurderingsperioden ikke har vedtak
> Refaktorert opprettelse/oppdatering revurdering.

- web/src/main/kotlin/no/nav/su/se/bakover/web/Extensions.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutes.kt
Merge denne når den bygger OK.
> Legg på behandlingId på lukkSøknad's audit logg

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/BrevTemplate.kt
- web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/komponenttest/AvslagKomponentTest.kt
- web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/komponenttest/AvslagManglendeDokumentasjonKomponentTest.kt
Vi har hatt et kort på dette en stund (fant det ikke i trello) og nå fikk vi et ønske fra fag.
> Bytt tittel i avslagsbrev

- web/src/main/kotlin/no/nav/su/se/bakover/web/JobberOgConsumers.kt
https://trello.com/c/5BixeHhq/1470-legge-inn-kj%C3%B8replan-for-konsistensavstemming-2023
> Fjernet passerte datoer, ny plan for 2023

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/SimulerUtbetalingRequest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/Utbetaling.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/GjenopptakAvYtelseService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/GjenopptakAvYtelseServiceTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/utbetaling/GjenopptaUtbetalingerServiceTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingServiceAndMocks.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingServiceImplTest.kt
Lider ikke av nested session-issues som de andre, men refaktorerte for å helhetens del.
> La sak opprette utbetaling for gjenopptak

- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/grunnlag/FradragsgrunnlagJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/grunnlag/GrunnlagsdataOgVilkårsvurderingerJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/regulering/RegulerAutomatiskRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/LeggTilFradragRevurderingRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/BeregningJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/FradragRequestJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/MånedsberegningJson.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/grunnlag/FradragsgrunnlagJsonTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/FradragRequestJsonTest.kt
frontend har at fradragets periode kan være null 🙃
> skill mellom request & response json for fradrag

- common/src/main/kotlin/no/nav/su/se/bakover/common/ApplicationConfig.kt
- common/src/test/kotlin/no/nav/su/se/bakover/common/ApplicationConfigTest.kt
- nais-dev.json
- nais-prod.json
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/personhendelser/PersonhendelseConsumer.kt
https://jira.adeo.no/plugins/servlet/desk/portal/541/FAGSYSTEM-247743
> Ta i bruk pdl-aiven & fjern on-prem kakfa stuff

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/OverlappendeÅpenBehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/regulering/OpprettEllerOppdaterRegulering.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/opprett/OpprettRevurdering.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/Sak.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/opprett/OpprettNySøknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/stønadsperiode/OppdaterStønadsperiode.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/SakTest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/GjenopptaYtelseServiceImpl.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/StansYtelseServiceImpl.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/opprett/KunneIkkeOppretteSøknadsbehandlingEx.kt
Gjenstår å gjøre det samme for revurdering og regulering.
> Sperr overlappende behandlinger ved opprettelse av søknadsbehandling

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/OverlappendeÅpenBehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/iverksett/IverksettSøknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/iverksett/KunneIkkeIverksetteSøknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/iverksett/avslå/IverksettAvslåttSøknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/iverksett/innvilg/IverksettInnvilgetSøknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/Stønadsvedtak.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/iverksett/IverksettSøknadsbehandlingRoute.kt
Klargjør for parallell behandling
> Rydd opp iverksett søknadsbehandling

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/SøknadsbehandlingService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceAttesteringTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutes.kt
Merk at vi er avhengig av denne sperren ved iverksetting.
> Fjern avventer kravgrunnlag-sperre ved send til attestering.

- client/src/main/kotlin/no/nav/su/se/bakover/client/kabal/KabalHttpClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/kabal/KabalRequest.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/kabal/KabalRequestMapper.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/kabal/KabalHttpClientTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/kabal/KabalRequestTest.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/kabal/KabalRequestTestData.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/BekreftVilkårsvurdertKlageTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/HentBrevutkastTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/OversendKlageTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/VilkårsvurderKlageTest.kt
- statistikk/src/test/kotlin/no/nav/su/se/bakover/statistikk/behandling/klage/StatistikkKlageTest.kt
- test-common/src/main/kotlin/KlageTestData.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/klage/AvsluttKlageTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/klage/AvvistKlageTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/klage/BekreftVilkårsvurderingerForKlageTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/klage/BekreftVurderingerForKlageTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/klage/OpprettKlageTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/klage/OversendKlageTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/klage/SendKlageTilAttesteringTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/klage/UnderkjennKlageTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/klage/VilkårsvurderKlageTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/klage/VurderKlageTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/services/klage/klageinstans/KlageinstanshendelseConsumerKafkaTest.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/services/personhendelser/PersonhendelseConsumerKafkaTest.kt
Venter med denne til vi har fikset frikort og postman kall til KA.
> Upgrade Kabal api version from v2 to v3

- .github/workflows/branch-deploy.yml
- .github/workflows/branch.yml
- .github/workflows/datapakker.yml
- .github/workflows/master.yml
- Dockerfile
- build.gradle.kts
- common/src/main/kotlin/no/nav/su/se/bakover/common/Utils.kt
- common/src/main/kotlin/no/nav/su/se/bakover/common/application/MånedBeløp.kt
- common/src/test/kotlin/no/nav/su/se/bakover/common/UtilsKtTest.kt
- datapakker/søknad/Dockerfile
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/LagBrevRequest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/beregning/LagBrevinnholdForBeregning.kt
This won't work of a bug that is fixed in gradle 8. Have to upgrade to that first.
> Upgrade to java 17 to 19

- database/src/main/kotlin/no/nav/su/se/bakover/database/sak/FerdigeBehandlingerRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/sak/ÅpneBehandlingerRepo.kt
- database/src/test/kotlin/no/nav/su/se/bakover/database/sak/FerdigeBehandlingerRepoTest.kt
- database/src/test/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepoTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/Behandlingssammendrag.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/SakRepo.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/SakService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/sak/SakServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/sak/SakServiceImplTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/sak/BehandlingsoversiktJson.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/AccessCheckProxy.kt
https://github.com/navikt/su-se-framover/pull/2758
> rename Behandlingsoversikt.kt til Behandlingssammendrag & legg inn periode

- client/src/main/kotlin/no/nav/su/se/bakover/client/skatteetaten/SigrunErrorJson.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/skatteetaten/SkatteClient.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/skatteetaten/SamletSkattegrunnlagTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/skatt/SkatteoppslagFeil.kt
Logger ikke så voldsomt lenger dersom vi personen eller året ikke finnes hos skatt.
> Legg til SigrunErrorJson

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/tidslinje/Tidslinje.kt
Håper dette fikser problemene i prod
> Reimplementere tidslinje

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/satser/SatsFactoryForSupplerendeStønad.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/satser/SatsFactoryForSupplerendeStønadUføreTest.kt
Vi har mottatt lovendringen som stemmer. Husk å oppdater kommentarerer når lovdata legger ut.
> Legg til nytt grunnbeløp og garantipensjon for mai 2023

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/PdfInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/skatt/SkattPdfJson.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/skatt/SkattemeldingsPdf.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/skatt/SkattPdfJsonTest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/skatt/SkattDokumentServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/skatt/SkattDokumentServiceImplTest.kt
pdf json er nå nesten helt identisk med database json. bare felt navn er endret. ellers bare en del mappings + tester
> egen json for skattegrunnlag pdf

- client/src/main/kotlin/no/nav/su/se/bakover/client/oppdrag/simulering/SimuleringResponseMapper.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/simulering/SimuleringResponseMapperTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/simulering/Kontooppstilling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/simulering/Simulering.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/simulering/TolketSimulering.kt
Flyttet en del av endringene her i tidligere commits. Merger denne slik at ting fremdeles fungerer og fortsetter med fix i neste branch.
> Forenkle kontooppstilling

- application/src/main/kotlin/no/nav/su/se/bakover/application/Application.kt
- build.gradle.kts
- web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/LocalApplicationWithTestdata.kt
- web-regresjonstest/src/test/resources/logging.properties
This will hopefully move more of the sysout/err -> logback
> Add SLF4J bridges

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/BeregnetSøknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/IverksattSøknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/KunneIkke.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/LukketSøknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/SimulertSøknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/SøknadsbehandlingService.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/SøknadsbehandlingTilAttestering.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/UnderkjentSøknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/VilkårsvurdertSøknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/beregn/KanBeregnes.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/beregning/EnsligBeregningTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/beregning/EnsligBorMedVoksneBeregningTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/beregning/EpsOver67BeregningTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/beregning/EpsUnder67BeregningTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/beregning/EpsUnder67OgUførFlyktningBeregningTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/StatusovergangTest.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/SøknadsbehandlingSkattTest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceLeggTilFradragsgrunnlagTest.kt
- test-common/src/main/kotlin/ArrowTestEx.kt
- test-common/src/main/kotlin/SøknadsbehandlingTestData.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutes.kt
Gjorde om Søknadsbehandling til sealed interface. Dette er steg 1. Det gjenstår noen TODOs der det var protected functions som ble public.
> Flytt Søknadsbehandling.beregn(...) til eget interface

- common/infrastructure/src/main/kotlin/no/nav/su/se/bakover/common/infrastructure/web/SuUserPlugin.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/LagBrevRequest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/PdfInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/AvvistKlage.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/IverksattAvvistKlage.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/KanGenerereBrevutkast.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/Klage.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/KlageTilAttestering.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/OversendtKlage.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/VurdertKlage.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/klage/KlageService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/klage/KlageServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/HentBrevutkastTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/IverksettAvvistKlageTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/klage/KlageRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/AccessCheckProxy.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/klage/ForhåndsvisBrevForKlageTest.kt
+ bruker saksbehandler navn somer registrert på klagen, og ikke innlogget bruker
> legg på attestantnavn på avvist klage

- kontrollsamtale/application/src/main/kotlin/no/nav/su/se/bakover/kontrollsamtale/application/KontrollsamtaleServiceImpl.kt
- kontrollsamtale/application/src/test/kotlin/no/nav/su/se/bakover/kontrollsamtale/domain/KontrollsamtaleServiceImplTest.kt
- kontrollsamtale/domain/src/main/kotlin/no/nav/su/se/bakover/kontrollsamtale/domain/KontrollsamtaleService.kt
- kontrollsamtale/infrastructure/src/main/kotlin/no/nav/su/se/bakover/kontrollsamtale/infrastructure/web/KontrollsamtaleJson.kt
- kontrollsamtale/infrastructure/src/main/kotlin/no/nav/su/se/bakover/kontrollsamtale/infrastructure/web/KontrollsamtaleRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/AccessCheckProxy.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/kontrollsamtale/KontrollsamtaleRoutesKtTest.kt
Gir frontend (saksbehandler) mulighet til å hente alle kontrollsamtalene for en sak. Kommer egen PR for framover.
> kunne hente alle kontrollsamtaler for en sak

- client/src/main/kotlin/no/nav/su/se/bakover/client/dokarkiv/JournalpostUtenforSak.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/pdf/SkattegrunnlagsPdfInnhold.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/pdf/PdfClientTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/skatt/SamletSkattegrunnlagForÅr.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/skatt/Skattedokument.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/skatt/FrioppslagSkattRequest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/skatt/KunneIkkeHenteOgLagePdfAvSkattegrunnlag.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/skatt/SkattDokumentService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/skatt/SkattDokumentServiceImpl.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/skatt/SkatteService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/skatt/SkatteServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/skatt/SkattDokumentServiceImplTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/skatt/SkatteServiceImplTest.kt
- test-common/src/main/kotlin/PdfTestData.kt
- test-common/src/main/kotlin/skatt/SkattegrunnlagTestData.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/skatt/SkatteRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/AccessCheckProxy.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/ServiceBuilder.kt
Lager ny PR med journalføring
https://github.com/navikt/su-se-framover/pull/3063
https://github.com/navikt/su-pdfgen/pull/87
> Frioppslag skatt - uten journalføring

- database/build.gradle.kts
- database/src/main/kotlin/no/nav/su/se/bakover/database/DatabaseBuilder.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepo.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandlinger.kt
- tilbakekreving/domain/src/main/kotlin/tilbakekreving/domain/opprett/TilbakekrevingsbehandlingRepo.kt
- tilbakekreving/infrastructure/src/main/kotlin/tilbakekreving/infrastructure/TilbakekrevingsbehandlingPostgresRepo.kt
- tilbakekreving/presentation/src/main/kotlin/tilbakekreving/presentation/api/common/TilbakekrevingsbehandlingJson.kt
- tilbakekreving/presentation/src/main/kotlin/tilbakekreving/presentation/api/opprett/OpprettTilbakekrevingsbehandlingRoute.kt
- web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/sak/SakJsonMatcher.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/sak/SakJson.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/sak/SakJsonTest.kt
Avhenger av branchen opprett-tilbakekrevingsbehandling (som den tok utgangspunkt i)
> Tilbakekrevingsbehandling på sak

- client/src/main/kotlin/no/nav/su/se/bakover/client/pdf/PdfClient.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/pdf/PdfGenerator.kt
- client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/pdf/PdfGeneratorStub.kt
- client/src/test/kotlin/no/nav/su/se/bakover/client/pdf/PdfClientTest.kt
- dokument/domain/src/main/kotlin/dokument/domain/pdf/PdfTemplate.kt
- dokument/domain/src/main/kotlin/dokument/domain/pdf/PdfTemplateMedDokumentNavn.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknad/SøknadPdfInnhold.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknad/SøknadPdfInnholdJsonTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/HentSøknadPdfTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/OpprettManglendeJournalpostOgOppgaveTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/SøknadTest.kt
kan flytte pdfGenerator interfacet til dokument
> SøknadPdfInnhold arver nå Pdfinnhold

- web/src/main/kotlin/no/nav/su/se/bakover/web/JobberOgConsumers.kt
```kotlin
4.januar(2024),
30.januar(2024),
28.februar(2024),
29.mars(2024),
25.april(2024),
24.mai(2024),
28.juni(2024),
30.juli(2024),
30.august(2024),
27.september(2024),
30.oktober(2024),
25.november(2024),
```
> legg inn konsistensavstemming for 2024

- common/domain/src/main/kotlin/no/nav/su/se/bakover/common/domain/tid/Tidspunkt.kt
- common/domain/src/test/kotlin/no/nav/su/se/bakover/common/domain/TidspunktTest.kt
Fikser https://github.com/navikt/su-se-bakover/security/code-scanning/360 comparator overloading. Legger også til mulighet og sammenligne tidspunkt - instant (begge veier)
> Add better Tidspunkt comparators

- database/src/main/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/vedtak/VedtakPostgresRepo.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/utbetaling/Utbetalinger.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/IverksattRevurdering.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/iverksett/innvilg/IverksettInnvilgetRevurdering.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/SakRepo.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/SakService.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/IverksattSøknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/iverksett/innvilg/IverksettInnvilgetSøknadsbehandling.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/VedtakRepo.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/sak/SakServiceImpl.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingServiceImpl.kt
- settings.gradle.kts
- web/build.gradle.kts
- web/src/main/kotlin/no/nav/su/se/bakover/web/Routes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/AccessCheckProxy.kt
- økonomi/application/build.gradle.kts
- økonomi/application/src/main/kotlin/økonomi/application/utbetaling/ResendUtbetalingService.kt
- økonomi/infrastructure/src/main/kotlin/økonomi/infrastructure/kvittering/consumer/UtbetalingKvitteringConsumer.kt
- økonomi/presentation/build.gradle.kts
- økonomi/presentation/src/main/kotlin/økonomi/presentation/api/ØkonomiRoutes.kt
- Mulighet for å resende utbetaling
> resend utbetaling

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/command/IverksettRevurderingDokumentCommand.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/jsonRequest/OpphørsvedtakPdfInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/jsonRequest/RevurderingAvInntektPdfInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/jsonRequest/RevurderingMedTilbakekrevingAvPengerPdfInnhold.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/brev/MapRevurderingTilDokumentCommand.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/brev/endringInntekt/MapRevurderingInntektTilDokumentKommando.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/brev/opphør/MapRevurderingOpphørTilDokumentKommando.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/brev/MapVedtakSomKanRevurderesTilDokumentCommand.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/Routes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/RevurderingRoutes.kt
måtte endre på ingen tester 🤔 
https://github.com/navikt/su-se-framover/pull/3385
> støtter forhåndsvisning av vedtaksbrevene uten fritekst

- kontrollsamtale/application/src/main/kotlin/no/nav/su/se/bakover/kontrollsamtale/application/KontrollsamtaleServiceImpl.kt
- kontrollsamtale/application/src/test/kotlin/no/nav/su/se/bakover/kontrollsamtale/domain/KontrollsamtaleServiceImplTest.kt
- kontrollsamtale/domain/src/main/kotlin/no/nav/su/se/bakover/kontrollsamtale/domain/KontrollsamtaleService.kt
- kontrollsamtale/domain/src/main/kotlin/no/nav/su/se/bakover/kontrollsamtale/domain/Kontrollsamtaler.kt
- kontrollsamtale/domain/src/main/kotlin/no/nav/su/se/bakover/kontrollsamtale/domain/endre/EndreKontrollsamtaleCommand.kt
- kontrollsamtale/domain/src/main/kotlin/no/nav/su/se/bakover/kontrollsamtale/domain/endre/KunneIkkeEndreKontrollsamtale.kt
- kontrollsamtale/domain/src/main/kotlin/no/nav/su/se/bakover/kontrollsamtale/domain/endre/SakEndreKontrollsamtale.kt
- kontrollsamtale/domain/src/main/kotlin/no/nav/su/se/bakover/kontrollsamtale/domain/hent/KunneIkkeHenteKontrollsamtale.kt
- kontrollsamtale/infrastructure/src/main/kotlin/no/nav/su/se/bakover/kontrollsamtale/infrastructure/web/EndreKontrollsamtaleRoute.kt
- kontrollsamtale/infrastructure/src/main/kotlin/no/nav/su/se/bakover/kontrollsamtale/infrastructure/web/KontrollsamtaleRoutes.kt
- kontrollsamtale/infrastructure/src/main/kotlin/no/nav/su/se/bakover/kontrollsamtale/infrastructure/web/OpprettKontrollsamtaleRoute.kt
- web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/komponenttest/IverksettTransactionKomponentTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/AccessCheckProxy.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/kontrollsamtale/KontrollsamtaleRoutesKtTest.kt
Har ikke lagt på logikk enda. Kun så vi kan teste noe fra frontend
> Legg til endepunkt for å endre kontrollsamtale

- dokument/domain/src/main/kotlin/dokument/domain/brev/BrevService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/brev/BrevServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/brev/BrevServiceImplTest.kt
- test-common/src/main/kotlin/DokumentTestData.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/dokument/DokumentRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/AccessCheckProxy.kt
- web/src/test/kotlin/no/nav/su/se/bakover/web/routes/dokument/DokumentRoutesKtTest.kt
en liten enhancement at dem kan klikke på dokument-id'en i kontrollsamtale oversikten, og få brevet
> kan hente et dokument ved bruk av id

- database/src/main/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepo.kt
- database/src/test/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepoTest.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/SakRepo.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/SakService.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/sak/SakServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/sak/SakServiceImplTest.kt
- test-common/src/main/kotlin/BosituasjonTestData.kt
- test-common/src/main/kotlin/vilkår/FormueVilkårTestData.kt
- vilkår/institusjonsopphold/application/src/test/kotlin/no/nav/su/se/bakover/institusjonsopphold/application/service/OpprettOppgaverForInstitusjonsoppholdshendelserTest.kt
- vilkår/vurderinger/domain/src/main/kotlin/vilkår/vurderinger/domain/Grunnlagsdata.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/sak/SakRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/AccessCheckProxy.kt
fronty: https://github.com/navikt/su-se-framover/pull/3645
> kan sjekke om eps har sak for en gitt brukers sak

- build.gradle.kts
- gradle/libs.versions.toml
- test-common/build.gradle.kts
https://github.com/junit-team/junit5-samples/blob/main/junit5-jupiter-starter-gradle/build.gradle
> Bruk anbefalt jupiter config

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/simulering/KryssjekkSaksbehandlersOgAttestantsSimulering.kt
* sb får forklaring
*  saksbehandler kjøre simulering på nytt så er problemet løst
> Forventet feil er info, sb får info om hva som skal gjøres

- vilkår/pensjon/domain/src/main/kotlin/vilkår/pensjon/domain/PensjonsVilkår.kt
- vilkår/pensjon/domain/src/main/kotlin/vilkår/pensjon/domain/VurderingsperiodePensjon.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/vilkår/pensjon/PensjonsVilkår.kt
Løser denne https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/.ds-navlogs-2025.05.18-001726?id=tAse6JYBRF04xvyywkTO
> Skal kunne redigere virk for alder

- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutes.kt
This reverts commit 7de714b5ced4538200494054323740a913fb0d03.
> Revert "Vis årsak direkte til sb (#2044)"

- client/src/main/kotlin/no/nav/su/se/bakover/client/pdf/SkattegrunnlagsPdfInnhold.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/klage/KlagePostgresRepo.kt
- database/src/main/resources/db/migration/V210__klage_sakstype.sql
- service/src/main/kotlin/no/nav/su/se/bakover/service/skatt/SkattDokumentServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/skatt/SkattDokumentServiceImplTest.kt
- test-common/src/main/kotlin/PdfTestData.kt
> Saktype alder for klage og skattegrunnlag

- database/src/test/kotlin/no/nav/su/se/bakover/database/statistikk/StatistikkHendelseRepoPostgresTest.kt
- statistikk/application/src/test/kotlin/no/nav/su/se/bakover/statistikk/stønad/StønadsstatistikkTest.kt
todo: vurdere å flytte over alle kafka publisher tester til db lag + publisher evt bare db. 
Må kanskje ha en for sakstats og en for stønad. tbd
> Fiks naming & tester

- client/src/main/kotlin/no/nav/su/se/bakover/client/oppgave/OppdaterOppgaveHttpClient.kt
Kan vurderes å gjøres i OppgaveHttpClient og da den går mot samme
> bedre logging for oppdateroppgave

- behandling/klage/domain/src/main/kotlin/behandling/klage/domain/VurderingerTilKlage.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/klage/KlagePostgresRepo.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/klage/KlageVurderingerRequest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/klage/VurderKlageTest.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/klage/KlageJson.kt
må inn før https://github.com/navikt/su-se-framover/pull/4246
testet ok
> Støtte omgjøring i klage

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/opprett/KunneIkkeOppretteRevurdering.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/opprett/OpprettRevurdering.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/opprett/OpprettRevurderingCommand.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/opprett/OpprettRevurderingResultat.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/statistikk/StatistikkEvent.kt
- domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/OpprettRevurderingTest.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/AvsluttRevurderingTest.kt
- service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceMocks.kt
- statistikk/application/src/main/kotlin/no/nav/su/se/bakover/statistikk/behandling/revurdering/revurdering/BehandlingsstatistikkMapperForRevurdering.kt
- test-common/src/main/kotlin/RevurderingTestData.kt
- vedtak/application/src/main/kotlin/no/nav/su/se/bakover/vedtak/application/VedtakServiceImpl.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OpprettRevurderingRoute.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/vedtak/VedtakRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/ServiceBuilder.kt
må inn med https://github.com/navikt/su-se-framover/pull/4253
> Knytt klage mot revurdering omgjøring

- domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/opprett/OpprettRevurdering.kt
rel https://github.com/navikt/su-se-bakover/pull/2208
> Knytt eget tiltakt mot vedtak behandlingid

- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/klage/KlageRoutes.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/services/AccessCheckProxy.kt
*Feiler på feltvaldering som ikke er i bruk...
> Fiks klage avvisning

- database/src/main/kotlin/no/nav/su/se/bakover/database/klage/KlagePostgresRepo.kt
- database/src/main/kotlin/no/nav/su/se/bakover/database/sak/FerdigeBehandlingerRepo.kt
- database/src/main/resources/db/migration/V219__ferdigstiltklage_dato.sql
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/FerdigstiltOmgjortKlage.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/Klage.kt
- domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/VurdertKlage.kt
- service/src/main/kotlin/no/nav/su/se/bakover/service/klage/KlageServiceImpl.kt
- web/src/main/kotlin/no/nav/su/se/bakover/web/routes/klage/KlageJson.kt
eget felt eller legge det i vedtaksvurdering json? Gikk for eget felt men det kan være misvisende for andre klagetyper. Men bruken indikerer kun for omgjøring da andre klagetyper trenger attestasjon.
Todo: Må legge inn datoer for de 2 i dev som ikke har dato.
> Ferdigstilttidspunkt klage omgjøring
