navikt/su-se-bakover

client/src/main/kotlin/no/nav/su/se/bakover/client/ClientsBuilder.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/ProdClientsBuilder.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/StubClientsBuilder.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/person/AdGraphApiClient.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/person/MicrosoftGraphApiClient.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/features/SuUserFeature.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/TestClientsBuilder.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/features/SuUserFeatureTest.kt

This is used for getting access to details of the logged-in user in a call
context. This can be used for example for getting the user's NAVIdent and for
handling authorization.

Add SuUserContext

---

database/src/test/kotlin/no/nav/su/se/bakover/database/DatabaseRepoTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/Behandling.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/VedtakInnhold.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/VedtakInnholdTestdataBuilder.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandlingsinformasjon.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregning.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Fradrag.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Månedsberegning.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/BehandlingTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/BeregningTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/services/brev/BrevService.kt

- Nya avslagsgrunner
- Avslår behandling nå hvis beregnet beløp er under minstebeløp (2% av full supplerende stønad)
Notes:
* Har lagt till ett nytt `Tilstand` nå som heter `BEREGNET_AVSLAG`, eftersom vi nå kan avslå en behandling p.g.a beregnet beløp er under minstebeløp. Provade att sette statusen tidigare till `VILKÅRSVURDERT_AVSLAG` men det introducerade många bugs.

Avslagsgrunner

---

database/src/main/resources/db/migration/V25__rename_beregnet_status.sql
database/src/test/kotlin/no/nav/su/se/bakover/database/DatabaseRepoTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/Behandling.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/BehandlingTest.kt

Also add migration script to convert values in db to correct ones:
`BEREGNET` / `BEREGNET_INVILGET` -> `BEREGNET_INNVILGET`

Fix typo - BEREGNET_INNVILGET

---

common/src/main/kotlin/no/nav/su/se/bakover/common/Config.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/Brukerrolle.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/Authentication.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/AuthenticationTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/Jwt.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/RoutesTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/TestEnvironment.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/features/SuUserFeatureTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/InntektRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/PersonRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/me/MeRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/sak/SakRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/utbetaling/stans/StansUtbetalingRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/utbetaling/start/StartUtbetalingRoutesKtTest.kt

This removes the need for the general "SU role", since we use the specific
roles (veileder, saksbehandler, attestant) more actively. We could probably now
remove the general role from Vault.
Do note that we don't have proper authorization on routes in place yet at this
point. Implementing this should be the next step.

Use specific role-based groups for authentication

---

database/src/main/kotlin/no/nav/su/se/bakover/database/søknad/SøknadRepoInternal.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/ServiceBuilder.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/behandling/BehandlingServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/oppgave/OppgaveService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/oppgave/OppgaveServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/SøknadServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/lukk/LukkSøknadServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/AccessCheckProxyTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/behandling/BehandlingServiceImplTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/NySøknadTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/lukk/LukkSøknadServiceImplTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/utbetaling/stans/StansUtbetalingRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/utbetaling/start/GjenopptaUtbetalingRoutesKtTest.kt

Var det slik du tenkte @hestad ? For enkelhetens skyld, så bare sender jeg dem videre til client.
Endret på .also{...}, det så ut som at selv om brev-ting failer, så kjøres den uansett. Tror det er slik at hvis brev ting failer, så vil vi ikke begynne å lukke oppgavem

oppgaveService

---

.github/workflows/branch.yml
client/src/main/kotlin/no/nav/su/se/bakover/client/ClientsBuilder.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/ProdClientsBuilder.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/StubClientsBuilder.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/dkif/DigitalKontaktinformasjon.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/dkif/Dkif.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/dkif/DkifClient.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/dkif/Kontaktinformasjon.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/person/PersonClient.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/dkif/DkifClientStub.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/person/PersonOppslagStub.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/dkif/DkifClientTest.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/inntekt/InntektClientTest.kt
common/src/main/kotlin/no/nav/su/se/bakover/common/Config.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/Person.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/brev/BrevServiceImplTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/PersonRoutes.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/TestClientsBuilder.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/PersonRoutesKtTest.kt

Vi trenger å vise noe informasjon om hvordan søkeren ønsker å få tilsendt kommunikasjon fra det offentlige, og det ligger i et register som heter KRR (Kontakt- og reservasjonsregisteret). I NAV kalles tjenesten som tilbyr dette DKIF (Digital kontaktinformasjon, tror jeg). 
Vi trenger i utgangspunktet mobil og epost, og hvorvidt de har reservert seg mot elektronisk kommunikasjon. Men vi får også ut målform/språk, som vi muligens senere trenger for å sende brev på riktig målform.

Henter kontaktinfo fra KRR via Dkif

---

service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/SøknadService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/SøknadServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/NySøknadTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadInnholdJson.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadJson.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutes.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutesKtTest.kt

Lade till ny json response før når man oppretter en ny søknad som innehåller saksnummer. Detta är så att vi i `Kvitteringen` kan visa saksnummer istället för en kryptisk uuid.

Saksnummer

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandlingsinformasjon.kt

Man ska inte behöva vurdere bosituasjonen till søker om han eller hon har fått avslag på ett eller flera vilkår. Då skal status på søknaden bara vara avslag och man skal till vedtaket direkt.

Exclude Bosituasjon & Ektefelle from vilkår in saksbehandling

---

database/src/main/resources/db/migration/V52__ektefellesVerdier_rename.sql
domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandlingsinformasjon.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/BehandlingsinformasjonTestdataBuilder.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/BehandlingTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/behandling/BehandlingsinformasjonTestData.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/behandling/FormueTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/behandling/BehandlingTestUtils.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingsinformasjonJson.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingJsonTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingTestUtils.kt

Bug fix: Frontend och backend refererar till forskjellige navn i json-objektet for ektefelles inntekt. Så just nu är det ikke muligt att ändra ektefelles inntekt i saksbehandlingen i Formue-steget.
* Har nå refaktorerat backenden så att det blir samma verdi (syns epsVerdier är mer korrekt än ektefellesVerdier).
* Har lagt till migreringsscript så att det som ligger i databasen endres också.

Rename ektefellesVerdier -> epsVerdier & add migration script

---

client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/person/PersonOppslagStub.kt
common/src/main/kotlin/no/nav/su/se/bakover/common/Config.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandlingsinformasjon.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/behandling/BehandlingsinformasjonJson.kt

If the person has some form of skjerming we won't know their name,
but we still need to save their fnr.

Allow saving EPS without name

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandling.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregningsgrunnlag.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/FradragFactory.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/BehandlingTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/behandling/BehandlingsinformasjonTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/BeregningsgrunnlagTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/beregning/BeregningMedFradragBeregnetMånedsvisTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/beregning/BeregningStrategyTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/beregning/EnsligBeregningTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/beregning/EnsligBorMedVoksneBeregningTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/beregning/EpsOver67BeregningTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/beregning/EpsUnder67BeregningTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/beregning/EpsUnder67OgUførFlyktningBeregningTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/EnsligStrategyTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/EpsOver67StrategyTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/EpsUnder67OgUførFlyktningStrategyTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/EpsUnder67Test.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/FradragFactoryTest.kt

-Pass forventet inntekt as a monthly sum covering the full period of the beregning.
-Changed periodization of fradrag to "duplicate" to provided fradrag for each month in its period.
-Mainly change test data, converting yearly sums to monthly etc.

Changing periodization of fradrag to use monthly sums as input.

---

client/src/main/kotlin/no/nav/su/se/bakover/client/oppdrag/simulering/SimuleringConfig.kt

Co-authored-by: Aryan Iranzamini <aryaniranzamini@gmail.com>

Deaktiver LoggingFeature i simuleringsklient for å unngå logging av full request/respons.

---

.github/workflows/branch.yml
client/src/main/kotlin/no/nav/su/se/bakover/client/ProdClientsBuilder.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/kafka/KafkaPublisherClient.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/kafka/KafkaPublisherClientTest.kt
common/src/main/kotlin/no/nav/su/se/bakover/common/Config.kt
common/src/test/kotlin/no/nav/su/se/bakover/common/ApplicationConfigTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/TestEnvironment.kt

- Oppretter ny producer dersom autorisasjon mot topic feiler.
- Tar vare på feilede meldinger, disse forsøkes resendes av repeterende task.

Håndtering av feil ved publisering av kafka-meldinger.

---

.github/workflows/branch.yml
client/src/main/kotlin/no/nav/su/se/bakover/client/oppdrag/IbmMqPublisher.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/person/PersonClient.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/person/PersonOppslagStub.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/person/PersonOppslag.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/behandling/IverksettBehandlingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/person/PersonService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/SøknadServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/AccessCheckProxyTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/RoutesTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/person/PersonRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutesKtTest.kt

Fjernet litt forskjellig støy fra loggen, hvor de største endringene var å sørge for at tilgangssjekken vår for person ikke kaller på det dekorerte person-endepunktet (som også kaller på kodeverk, skjermingstjenesten og DKIF), og å fjerne OPTIONS-kall fra request-loggingen.

Fjern støy fra loggen

---

nais.yml

This is to prepare for the new authentication flow, where su-se-framover
will call us with on-behalf-of tokens. Ref.
https://doc.nais.io/security/auth/azure-ad/#pre-authorization_1

Specify su-se-framover as a pre-authorized app

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/Person.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/søknad/lukk/AvvistSøknadBrevRequestTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/behandling/BehandlingTestUtils.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/behandling/LagBrevUtkastForBehandlingTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/behandling/OpprettManglendeJournalpostOgBrevForIverksettingerTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/brev/BrevServiceImplTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/HentSøknadPdfTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/OpprettManglendeJournalpostOgOppgaveTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/lukk/LukkSøknadServiceImplTest.kt

Vi har en del sånne rundt omkring i testene våre, som er ganske kjipe å oppdatere når man legger til et felt i personalia:
```   
private val person = Person(
ident = Ident(
fnr = Fnr(fnr = "12345678901"),
aktørId = AktørId(aktørId = "123")
),
navn = Navn(fornavn = "Tore", mellomnavn = "Johnas", etternavn = "Strømøy"),
telefonnummer = null,
adresse = null,
statsborgerskap = null,
kjønn = null,
fødselsdato = null,
adressebeskyttelse = null,
skjermet = null,
kontaktinfo = null,
vergemål = null,
fullmakt = null,
)
```
Har ikke tenkt noe særlig på om defaultene kan/bør være noe annet enn `null`, men det kan jo også settes etterhvert hvis man finner noe bedre.

Bruk defaultverdier på Person for å gjøre instansiering i tester enklere

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknad/SøknadPdfInnhold.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknad/SøknadPdfInnholdJsonTest.kt

Denne viste tidligere frem UTC-tidspunktet, altså en time før korrekt tidspunkt.

Bruk gjeldende tidssone for utskriftstidspunkt i søknads-PDF

---

build.gradle.kts

https://github.com/Unleash/unleash-client-java/commit/5e4bb2e0cedb57e9134efff8ec48d8c370c054b5

Bump unleash client to a version that uses slf4j instead of log4j2

---

client/src/main/kotlin/no/nav/su/se/bakover/client/person/PdlClient.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/oppdrag/SimuleringStub.kt
common/src/main/kotlin/no/nav/su/se/bakover/common/Extensions.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/me/MeRoutes.kt

Når vi får perioder med nullutbetaling vil de relle simuleringene ikke inneholde disse periodene.
SimuleringStub vil nå også gjøre dette, i stedet for å legge til perioder med nullutbetaling.

Endre SimuleringStub til å oppføre seg som det faktiske simuleringssystemet

---

service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/BrevutkastForRevurderingRoute.kt

Dette er gjort som et eget endepunkt for å (forhåpentligvis) forhindre at man sender inn tom fritekst uten at man mener det.

Legg til endepunkt for å hente et eksisterende revurderingsbrev

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/OppdaterRevurderingServiceTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OppdaterRevurderingsperiodeRoute.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OppdaterRevurderingsperiodeRouteKtTest.kt

Dersom man oppretter en revurdering og aldri går lenger enn beregnings/simuleringssteget, vil man at forhåndsvarsling skal være "IngenForhåndsvarsling" for G-regulering, men null for de andre årsakene.
Så hvis saksbehandler årsaken fra/til G-regulering, burde forhåndsvarling følge etter.
Legger og inn en guard, slik at vi ikke kan oppdatere revurderinger vi allerede har forhåndsvarslet.

Fix forhåndsvarsel ved oppdatering til G-regulering

---

common/src/main/kotlin/no/nav/su/se/bakover/common/Config.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/Grunnbeløp.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/GrunnbeløpTest.kt

Legger til en G-verdi for 2021 hvis vi er i et ikke-produksjonsmiljø. Logger dersom verdien er aktiv, slik at vi kan sjekke at logg-innslaget ikke finnes i produksjon når vi deployer.

Legg til fiktiv G-verdi (kun aktiv i utviklings- og testmiljø)

---

database/src/main/kotlin/no/nav/su/se/bakover/database/søknadsbehandling/SøknadsbehandlingPostgresRepo.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/søknadsbehandling/SøknadsbehandlingPostgresRepoTest.kt

Fiks av "rogue" sql som feilaktig oppdaterer alle søknadsbehandlinger i databasen hver gang en søknadsbehandling med tilstanden "vilkårsvurdert_xx" lagres.

Lagt til manglende where clause med id for oppdatering av behandling.

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/BrevInnhold.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/LagBrevRequest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/lukk/LukkSøknadServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/vedtak/FerdigstillVedtakService.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImplTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceBrevTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/vedtak/FerdigstillVedtakServiceImplTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/Revurderingsfeilresponser.kt

Tok også i bruk den enklere `hentNavnForNavIdent` andre steder vi bare trenger navn på saksbehandler/attestant, i stedet for `hentBrukerinformasjonForNavIdent` som henter ut hele objektet.

Legg til saksbehandlernavn i forhåndsvarselbrev

---

README.md
build.gradle.kts
clean_lint_and_build.sh
gradle/wrapper/gradle-wrapper.properties
lint_and_build.sh

Et pre-steg for å bytte til java 16 (og senere java 17 som er LTS)
Måtte også bytte ktlint-plugin, da vi ikke kunne oppgradere den vi brukte lenger (vs. å begynne med issues/PRs inn der)
Det kan hende du må kjøre rm ./.git/hooks/pre-commit fra den gamle ktlint-pluginen

Oppgrader Gradle fra 6.8.3 til 7.0

---

client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/oppdrag/SimuleringStub.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/grunnlag/VilkårsvurderingPostgresRepo.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/grunnlag/VilkårsvurderingRepo.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/grunnlag/VilkårsvurderingPostgresRepoTest.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/søknadsbehandling/SøknadsbehandlingPostgresRepoTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vilkår/Vilkår.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/RevurderingTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/vedtak/VedtakPåTidslinjeTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/vedtak/VedtakTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/vilkår/UførhetTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/vilkår/VilkårsvurderingerTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/vilkår/VurderingsperiodeTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/visitor/FinnAttestantVisitorTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/grunnlag/VilkårsvurderingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/vilkår/LeggTilUførevurderingRequest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RegulerGrunnbeløpServiceImplTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingIngenEndringTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImplTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingTestUtils.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/grunnlag/UførevilkårJson.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/LeggTilGrunnlagRevurderingRoutes.kt
web/src/test/kotlin/no/nav/su/se/bakover/service/vilkår/LeggTilUførevurderingerRequestTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/grunnlag/GrunnlagsdataJsonTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/BeregnOgSimulerRevurderingRouteKtTest.kt

* Oversetter avslag til null-verdier for grunnlag
* Kan plassere vurderingsperioder uten grunnlag på tidslinje
* Gjennomfører ny beregning selv om vilkår fører til opphør.
* Vis opphørsdato som fra-dato i simuleringsstub.
* Oppdaterer alle felter i behanlingsinformasjon/uførhet med informasjon fra første vurderingsperiode.

Revurdering av vilkår - retting av diverse småfeil og problemer.

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/Garantipensjonsnivå.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/GarantipensjonsnivåTest.kt

Trengs for testing av G-regulering, skal ikke dukke opp i produksjon.

Legg til estimert garantipensjon for 2021

---

database/src/main/kotlin/no/nav/su/se/bakover/database/beregning/BeregningMapper.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/beregning/BeregningMapperTest.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/beregning/TestBeregning.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregningsgrunnlag.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Månedsberegning.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/PeriodisertBeregning.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/RevurdertBeregning.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/SlåSammenEkvivalenteMånedsberegningerTilBeregningsperioder.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/Fradrag.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/FradragFactory.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/FradragStrategy.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/IkkePeriodisertFradrag.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/PeriodisertFradrag.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/beregning/FradragsMapper.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/VurderOmBeregningHarEndringerIYtelseTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/beregning/BeregningMedFradragBeregnetMånedsvisTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/EnsligStrategyTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/EpsOver67StrategyTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/EpsUnder67OgUførFlyktningStrategyTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/EpsUnder67Test.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/fradrag/IkkePeriodisertFradragTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/beregning/TestBeregning.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RegulerGrunnbeløpServiceImplTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/BeregningJson.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/FradragJson.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/BeregningTestUtils.kt

Har tatt en titt i produksjonsdatabasen med spørringen: `select beregning-> ‘fradrag’ from behandling where beregning is not null and beregning::text like ‘%total%’;` som ga 0 rows

Bytt funksjonene i Fradrag's-interfacet til val's

---

client/src/main/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveHttpClient.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveHttpClientTest.kt

saksnummer/søknadid finnes allerede på beskrivelsen i oppgaven fra når den ble opprettet. Trengs ikke å bli gjentatt

Fjern rad med saksnummer/søknadid på endre/lukke oppgave

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/LagBrevRequest.kt

Quickwin som ikke gjør noe med at vi burde omstrukturere hvordan vi bygger brev-DTOene våre.

Bare vis beregning i opphørsbrev hvor det er relevant

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregning.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/simulering/Simulering.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/IdentifiserSaksbehandlingsutfallSomIkkeStøttes.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/VurderOpphørVedRevurdering.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vilkår/Vilkår.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/beregning/BeregningMedFradragBeregnetMånedsvisTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/IdentifiserRevurderingsutfallSomIkkeStøttesTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/IdentifiserSaksbehandlingsutfallSomIkkeStøttesTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/RevurderingTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/VurderOpphørVedRevurderingTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/vilkår/VilkårsvurderingerTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RegulerGrunnbeløpServiceImplTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingBeregnOgSimulerTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingIngenEndringTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingSendTilAttesteringTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImplTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/Resultat.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/BeregnOgSimulerRevurderingRoute.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/SendRevurderingTilAttestering.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/BeregnOgSimulerRevurderingRouteKtTest.kt

Endret logikk for opphør til å være i tråd med mål satt for MVP:
Generelt:
- Alle opphør må gjøres fra dato lik revurderingsperiode-start
- Opphør for deler av perioden støttes ikke.
- Kombinasjon av opphør og endringer i ytelse støttes ikke
- 0-beløp for alle måneder i revurderingsperioden fører til opphør (uavhengig av framtid/fortid)
Vilkår:
- Opphør for hele revurderingsperioden dersom minst 1 vilkår er avslått.
- Opphør av flere vilkår støttes ikke (må utvides og lages logikk for etterhvert)
Inntekt:
Framover i tid:
- Minst 1 måned med 0-beløp gir opphør
Bakover i tid:
- 0-beløp bakover i tid (før dagens dato) gir ikke opphør, men håndteres som en normal endring (tilbakereving/etterbetaling)

Ny logikk for opphør ved revurdering

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/Utbetalingsstrategi.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/utbetaling/UtbetalingsstrategiOpphørTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/OppdaterRevurderingServiceTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/OpprettRevurderingServiceTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImplTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OppdaterRevurderingsperiodeRoute.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OpprettRevurderingRoute.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/Revurderingsfeilresponser.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OppdaterRevurderingsperiodeRouteKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OpprettRevurderingRouteKtTest.kt

Fjerner sperrer som forhindrer opprettelse av revurderinger tilbake i tid. 
Åpner for en del tilfeller som ikke støttes, må avventes til nye sperringer lagt til av https://github.com/navikt/su-se-bakover/pull/324 er på plass.

Åpne for å kunne revurdere tilbake i tid.

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/simulering/TolketSimulering.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/simulering/TolketSimuleringTest.kt

Krever ikke lenger at en feilutbetaling skal inneholde en detalj for "ordinær" utbetaling ved tolkning. Dette er kun tilfelle for feilutbetalinger hvor det gjenstår et restbeløp som faktisk skal/skulle utbetales.

Tolkning av fullstendig tilbakekreving for måneder.

---

web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/Extensions.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/person/PersonRoutes.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/sak/SakRoutes.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/RoutesTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/person/PersonRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/sak/SakRoutesKtTest.kt

Har erstattet `GET /person/{fnr}` og `GET /saker?fnr={fnr}` med POSTs til hhv. `/person/søk` og `/saker/søk` med fnr som parameter i body. Tok da også med søket på saker med saksnummer, altså `POST /saker/søk` med saksnummer som parameter i body.
Tas i bruk i klient i https://github.com/navikt/su-se-framover/pull/837

Bruk POST i stedet for GET på kall som inkluderer fnr

---

client/src/main/kotlin/no/nav/su/se/bakover/client/oppdrag/simulering/SimuleringRequestBuilder.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/simulering/SimuleringRequestBuilderTest.kt

Ved simulering av f.eks opphør sender vi med den siste utbetalingslinjen samt en dato hvor opphøret skal starte å gjelde fra. I tilfeller hvor opphørsdatoen er tidligere enn datoen på siste utbetalingslinje må vi bruke denne for å få med eventuelle utbetalingsperioder forut for siste utbetalingslinje i simuleringen.

Bruk tidligste dato av "datoStatusFom" og "datoVedtakFom".

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/grunnlag/SjekkOmGrunnlagErKonsistent.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/grunnlag/SjekkOmGrunnlagErKonsistentTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/grunnlag/KonsistensproblemJson.kt

Tanke; en komponent som kan håndtere konsistenssjekk av grunnlag på alle tidspunkter vi måtte ha behov for det (både for revurdering og søknadsbehandling)
"Modulær" for å kunne støtte at man i enkelte tilfeller kun ønsker å sjekke konsistens mellom enkelte typer grunnlag (f.eks når man legger til nytt grunnlag), eller i tilfeller hvor man mangler mye grunnlag (f.eks søknadsbehandling) - i tillegg til at man kan lage kompositter som sjekker mer/mindre (f.eks burde vi sjekke alt før vi beregner). Laget slik at det er konsumenten som må ta stilling til hvordan eventuelle feil håndteres, slik at disse kan brukes på flere måter (f.eks hard stop med feilmelding, eller feedback-meldinger)
Har bare tatt i bruk for opprettelse/oppdatering av revurdering til nå, men på sikt hadde det vært fint om …

Komponent for konsistenssjekk av grunnlag

---

service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImplTest.kt

-Unngår feilmeldinger om at "forhåndsvarsel allerede er sendt" selv om man har valgt at forhåndsvarsel ikke skal sendes.
-Sjekker om revurderingen lar seg sende til attestering før forhåndsvarsel sendes ut
-Gjort det mulig å endre fra "ingen forhåndsvarsel" til "forhåndsvarsel", noe som sannsynligvis kan være nyttig for tilfeller hvor attestering underkjennes.
Frontend: https://github.com/navikt/su-se-framover/pull/872

Refaktorert logikken for valg av forhåndsvarel/attestering.

---

client/src/main/kotlin/no/nav/su/se/bakover/client/ProdClientsBuilder.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/person/PdlClient.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/person/PdlClientTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/SøknadServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/OpprettManglendeJournalpostOgOppgaveTest.kt

-Benytter systembruker-token ved kall fra drifts-endepunkt for manglende journalpost og oppgaver.
-Unngår unødvendig dobbelt-kall til STS ved bruk av systembruker-token.

Fjerner toggle for bruk av on-behalf-of token mot PDL.

---

database/src/main/resources/db/migration/V93__migrer_formue_behandlingsinformasjon_til_grunnlagsdata.sql

- Migrerer kun behandlingsinformasjon fra revurderinger som ikke har grunnlagsdata_formue idag
- fraogmed / tilogmed -dato er lik revurderingens periode (så det blir 1-1 mapping mellom revurdering og grunnlag for formue)

Migrate behandlingsinformasjon from revurdering to grunnlagsdata

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/simulering/Simulering.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/simulering/SimuleringTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingServiceImplTest.kt

TL;DR: Nettobeløpet innebefatter skatt, og endres av oppdrag over tid.
Eksempelvis så vil en saksbehandling for måneden juli gjort i juli føre til at oppdrag bruker brukerens tabellkort for denne måneden, men hvis attestant kjører simuleringen i august, så vil oppdrag bruke den faste skatteprosenten på 32%. Denne vil typisk være høyere enn tabellkortet (som gjerne kan gi 0 kr i skatt), og da vil nettobeløpet være forskjellig i saksbehandlers og attestants simulering.

Fjern nettobeløp fra kontrollsimuleringssjekk

---

database/src/main/kotlin/no/nav/su/se/bakover/database/DatabaseEx.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/sak/SakRestansRepo.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepoTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/SakRestans.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/sak/SakServiceImplTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/sak/SakRestansJson.kt

Dette betyr også at tidspunktet fjernes for nye søknader, som det jo ikke er startet behandling på enda.
Helt konkret så er endringen at vi endrer feltnavn fra `opprettet` til `behandlingStartet`, og tillater at det er null for nye søknader.

Oppgi behandlingsstart-tidspunkt for de åpne behandlingene

---

service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/brev/BrevService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/brev/BrevServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/AccessCheckProxyTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/brev/BrevServiceImplTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/dokument/DokumentJson.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/dokument/DokumentRoutes.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/dokument/DokumentJsonKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/dokument/DokumentRoutesKtTest.kt

Enkelt endepunkt som søker opp dokumenter knyttet til en gitt id. I tillegg til id tar endepunktet i mot informasjon om hvilken type id det er snakk om (sak/vedtak/revurdering). Det legges dermed opp til at den som kaller selv må avgjøre hva man ønsker å slå opp dokumenter for (kan bruke samme endepunkt for å hente ut alle dokumenter for en sak, et spesifikt vedtak etc). Valgte denne varianten fremfor å la alle domeneobjektene ha dokumenter knyttet til seg.

Endepunkt for uthenting av persisterte dokumenter.

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/grunnlag/Grunnlag.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/grunnlag/Grunnlagsdata.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/grunnlag/SjekkOmGrunnlagErKonsistent.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Statusovergang.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/grunnlag/BosituasjonTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/grunnlag/FradragsgrunnlagTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/grunnlag/GrunnlagsdataOgVilkårsvurderingerTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/StatusovergangTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutes.kt

eksempel: 
stønadsperiode: 01.2022 - 12.2022
fradrag: 01.2022 - 06.2022
oppdaterer periode: 04.2022 - 12.2022
fradrag blir: 04.2022 - 06.2022
stønadsperiode: 01.2022 - 12.2022
fradrag: 01.2022 - 06.2022
oppdaterer periode: 01.2021 - 12.2021 (går ett år tilbake)
fradrag blir: 01.2021 - 12.2021
saksbehandler må sjekke over fradragene uansett etter endring av stønadsperiode, så hvis det ikke finnes en overlapp mellom den nye perioden, og fradrags-perioden, blir dem bare satt til hele stønadsperioden.

oppdaterer periodene i grunnlag når stønadsperioden endres

---

database/src/main/kotlin/no/nav/su/se/bakover/database/vedtak/VedtakPosgresRepo.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/Vedtak.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/VedtakVisitor.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/visitor/LagBrevRequestVisitor.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/visitor/SkalSendeBrevVisitor.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/visitor/LagBrevRequestVisitorTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/visitor/SkalSendeBrevVisitorTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/OppdaterRevurderingServiceTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImplTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceIverksettTest.kt
test-common/src/main/kotlin/VedtakTestData.kt

-Innført mulighet for å utlede opphørsgrunner direkte fra opphørsvedtak.
-Sterkere typer på behandlinger knyttet til vedtak.
https://trello.com/c/WLgqBrmO/911-brev-for-opph%C3%B8r-pga-inntekt-viser-ikke-%C3%A5rsak

Få med opphørsgrunn i brevet, også dersom det er høy inntekt.

---

web/src/main/kotlin/no/nav/su/se/bakover/web/services/utbetaling/kvittering/UtbetalingKvitteringIbmMqConsumer.kt

Ser ut som måten man fanger opp at køen f.eks. går ned er ved å sette opp en exceptionListener. Logger bare i første omgang, så får vi se senere om vi også ønsker å prøve å reconnecte e.l.

Lytt på exceptions fra JMS/MQ

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/IdentifiserSaksbehandlingsutfallSomIkkeStøttes.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/IdentifiserRevurderingsutfallSomIkkeStøttesTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt

IdentifiserSaksbehandlingsutfallSomIkkeStøttes flagget feilaktig revurderinger av opphør som `ikke støttet` dersom revurderingsperioden var forskjellig fra stønadsperioden, og noen av fradragene fra stønadsperioden da var *utenfor* revurderingsperioden.

Fiks bug som stopper opphør unødvendig

---

client/src/main/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveHttpClient.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/oppgave/OppgavebeskrivelseMapper.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveHttpClientTest.kt
common/src/main/kotlin/no/nav/su/se/bakover/common/periode/Periode.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/Kodeverk.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppgave/OppgaveConfig.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Stønadsperiode.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/SøknadsbehandlingTest_Søknadstype.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/SøknadsbehandlingVisitorTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/SøknadServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/NySøknadTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/OpprettManglendeJournalpostOgOppgaveTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/SøknadserviceOgMocks.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceAttesteringTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceLeggTilFradragsgrunnlagTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceUnderkjennTest.kt
test-common/src/main/kotlin/SøknadsbehandlingTestData.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutesKtTest.kt

La inn sjekk på ulovlige tilstander som ved opprettelse/oppdatering av søknadsbehandling som kaster exception; siden det finnes behandlingskombinasjoner der vi ikke kan avgjøre om det vil være en førstegangssøknad eller ny periode (typisk ved fler åpne søknadsbehandlinger)

Skill mellom førstegang og ny periode ved opprettelse av oppgaver

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/Sak.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Statusovergang.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/SøknadsbehandlingTest_Søknadstype.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/SøknadServiceImpl.kt

Siden det opprettes en oppgave med en gang en søknad sendes inn, vil vi nå få en 500 ved søknadsinnsending dersom det finnes en åpen søknadsbehandling. Dette fikser i hvert fall slik at hvis det finnes en iverksatt innvilget, så blir det ny periode. Det vil fremdeles feile dersom det kun er åpne søknader.
Ryddet opp litt generelt og la på mer beskrivende tekst.

Sett oppgave til NyPeriode dersom det finnes en annen iverksatt innvilget

---

service/src/main/kotlin/no/nav/su/se/bakover/service/statistikk/Statistikk.kt

javadocs som samsvarer med den beskrivelsen vi har i de forskjellige scheman. Dette er så att vi enklare skal ha tilgang till beskrivelsen under utvikling.

Lagt til javadocs for statistikk

---

common/src/main/kotlin/no/nav/su/se/bakover/common/periode/Periode.kt
common/src/test/kotlin/no/nav/su/se/bakover/common/periode/PeriodeTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/Sak.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Statusovergang.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/Vedtak.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/SakTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/StatusovergangTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/ServiceBuilder.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/GjenopptakAvYtelseServiceTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceOppdaterStønadsperiodeTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingTestUtils.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/utbetaling/GjenopptaUtbetalingerServiceTest.kt
test-common/src/main/kotlin/RevurderingTestData.kt
test-common/src/main/kotlin/VedtakTestData.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutes.kt

-Stønadsperioder som er delvis opphørt ansees bare som "aktiv" for perioden hvor ytelsen ikke er opphørt
-Stønadsperioder som er helto opphørt ansees ikke som aktive
-Sperrer fra å velge stønadsperioder forut for aktive eksisterende stønadsperioder

Tillat innvilgelse av ny periode dersom ikke overlapp med aktiv periode

---

.env.template
client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/person/PersonOppslagStub.kt
common/src/main/kotlin/no/nav/su/se/bakover/common/Config.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/person/PersonRoutesKtTest.kt

For enklere å kunne switche mellom en vanlig bruker og en kode 6-bruker når man tester lokalt. Gjør det også enklere å teste at søker *ikke* har kode 6, mens ektefelle *har* kode 6.

Legg til mulighet for å ha en kode 6-bruker lokalt

---

service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/Resultat.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/LeggTilGrunnlagBosituasjonRoutes.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/GrunnlagBosituasjonEpsSkjermetRoutesTest.kt

Håndterer dette som et eget endepunkt for å ikke blande det inn i logikken som også setter mer info om EPS på behandlingsinformasjon.
https://github.com/navikt/su-se-framover/pull/1307

Lagre EPS med adressebeskyttelse eller skjerming

---

service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/vedtak/FerdigstillVedtakService.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/vedtak/FerdigstillVedtakServiceImplTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/services/utbetaling/kvittering/UtbetalingKvitteringConsumer.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/services/utbetaling/kvittering/LokalKvitteringJobTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/services/utbetaling/kvittering/UtbetalingKvitteringConsumerTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/services/utbetaling/kvittering/UtbetalingKvitteringResponseTest.kt

Vi har en race-condition mellom saksbehandler-initiert iverksett (som bl.a. legger en melding på kø til oppdrag, og så persisterer utbetaling og vedtak), og kvittering-handleren fra Oppdrag, som prøver å oppdatere/bruke den nevnte utbetalingen og vedtaket.
Vi har hatt en Grei Nok™ fiks som sover i et sekund og prøver på nytt i kvittering-handleren, men denne har kun tatt for seg feil ved henting av utbetalingen og ikke vedtaket (som den gjør nå). 
Logger også litt mer slik at vi kan spore bedre hva som faktisk skjer i hvilken rekkefølge når vi iverksetter.

Håndter begge feilsituasjoner i kvittering-listeneren fra Oppdrag

---

web/src/test/kotlin/no/nav/su/se/bakover/web/TestDatabaseBuilder.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/TestEnvironment.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/TestServicesBuilder.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/avstemming/AvstemmingRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/me/MeRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/GjenopptaUtbetalingRouteKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutesKtTest.kt
web/src/test/resources/logback-test.xml

-Sparer litt tid ved å gjøre oppsett av migrert embedded database til opt-in funksjonalitet.
-Endret en del tester som "stopper" i web-laget/mocked service til å ikke benytte en migrert embedded database da dette ikke fremstår hensiktsmessig
-Undertrykker litt log-støy fra kafka/zookeeper/confluent for tester i web

Liten opprydding i web-tester

---

database/src/main/resources/db/migration/V109__fjern_vedtakId_fra_avslutt_revurdering_dokument.sql
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImplTest.kt

Noen plasser vil vi gjerne knytte dokumentet til flere ID'er, så har ikke lagt til sperre for at vi kan bare knytte den til 1 behandling. tenker i utgangspunktet at vi fikser buggen, så ser vi på å gjøre det litt safere en annen gang.

fjern kobling til vedtakId for avslutt-revurdering brev & migrer DB

---

database/src/main/kotlin/no/nav/su/se/bakover/database/DatabaseBuilder.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/nøkkeltall/NøkkeltallPostgresRepo.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/TestDataHelper.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/nøkkeltall/NøkkeltallPostgresRepoTest.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/søknadsbehandling/SøknadsbehandlingPostgresRepoTest.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/vedtak/VedtakPostgresRepoTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/nøkkeltall/Nøkkeltall.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/nøkkeltall/NøkkeltallJson.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/nøkkeltall/NøkkeltallRoutesKtTest.kt

Regner ut løpende saker som antallet aktive innvilgelser minus antallet aktive opphør (hvor "aktive" betyr at dagens dato er innenfor perioden for vedtaket).

Hent nøkkeltall for løpende saker

---

service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/lukk/LukkSøknadServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/statistikk/BehandlingStatistikkMapperTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/statistikk/StatistikkServiceImplTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/lukk/LukkSøknadServiceImplTest.kt

I #605 byttet jeg ut noen mocks med testdata fra testdata-filene. Byttet ut alle mocks i de testene i de to filene nå når jeg først var i gang, så her er pr på de siste
Edit: La også ved at vi kun sender èn event ved lukking av saksbehandling

En event ved lukking av saksbehandling + Bruk eksisterende testdata på resten av testene

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/Sak.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/SakTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/sak/SakJson.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/sak/SakRoutes.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutes.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/sak/SakJsonTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutesKtTest.kt

Tillater heller ikke stans dersom det er opphold mellom stønadsperioder, uten at jeg er helt sikker på om dette er like problematisk. Vi plukker opp igjen problemstillingen dersom fag melder om behov for å stanse på en sak hvor vi har fjernet knappen. John Are er happy med dette.

Fjern muligheten for å stanse utbetalinger ved opphør

---

database/src/main/kotlin/no/nav/su/se/bakover/database/klage/KlagePostgresRepo.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/klage/KlagevedtakPostgresRepo.kt
database/src/main/resources/db/migration/V119__klage_endringer_i_vedtak_og_constraints.sql
database/src/test/kotlin/no/nav/su/se/bakover/database/TestDataHelper.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/klage/KlagePostgresRepoTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/Sak.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/Klage.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/KlageRepo.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/OpprettetKlage.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/klage/KlageServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/klage/OpprettKlageTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/klage/KlageRoutes.kt

Vi kommer trenge å lagre våre vedtak knyttet til klagen, så då er nyttigt å tydliggjøre att (de nåværande) klagevedtak er vedtaken fra klageinstans og ikke våre vedtak.
Har i tillegg lagt til en unique constraint på journalpostId sån att man ikke kan legge in 2 klagebehandlinger på de samme journalførte dokumentet.

Refaktorer klagevedtak til klageinstansvedtak

---

client/src/main/kotlin/no/nav/su/se/bakover/client/oppdrag/utbetaling/UtbetalingMqPublisher.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/stubs/oppdrag/UtbetalingStub.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/DatabaseBuilder.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/utbetaling/UtbetalingPostgresRepo.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/TestDataHelper.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/utbetaling/UtbetalingPostgresRepoTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/utbetaling/UtbetalingPublisher.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/utbetaling/UtbetalingRepo.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Statusovergang.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/StatusovergangTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/ServiceBuilder.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/kontrollsamtale/KontrollsamtaleService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/GjenopptakAvYtelseService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/GjenopptakAvYtelseServiceTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceIverksettTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingTestUtils.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/utbetaling/GjenopptaUtbetalingerServiceTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/utbetaling/StansUtbetalingServiceTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingServiceImplTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutesKtTest.kt

Transaksjon i søknadsbehandling.

Trans for søknadsbehandling

---

common/src/main/kotlin/no/nav/su/se/bakover/common/Config.kt
common/src/test/kotlin/no/nav/su/se/bakover/common/ApplicationConfigTest.kt
web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/SharedRegressionTestData.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/services/avstemming/KonsistensavstemmingJob.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/services/dokument/DistribuerDokumentJob.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/services/klage/KlageinstansvedtakJob.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/services/personhendelser/PersonhendelseOppgaveJob.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/TestEnvironment.kt

ref: https://trello.com/c/Dgfi22gW/1112-initiell-delay-p%C3%A5-jobbene-v%C3%A5re-for-%C3%A5-v%C3%A6re-sikre-p%C3%A5-at-leader-elector-er-oppe-etter-restart

Legg på 5 min initiell delay på alla job:er som kjører ved oppstart

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/kontrollsamtale/Kontrollsamtale.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/kontrollsamtale/KontrollsamtaleTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/kontrollsamtale/KontrollsamtaleService.kt

Vi hadde en feilaktig satt opp if-sjekk som gjorde at kontrollsamtale-innkallinger ikke ble annullert i `annuller`-kallet. Setter samtidig dokument-id på innkalte, som feilaktig forsvant i en refaktorering.

Fix bug ved annullering av kontrollsamtale-innkallinger

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/Utbetaling.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/IverksettRevurderingTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingIngenEndringTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceIverksettTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/IverksettRevurderingRoute.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutes.kt

Iverksetting av søknadsbehandling og revurderinger kjøres som en transaksjon. Der har vi noen bugs og mangler i dag. Dersom kontrollsamtale feiler, ignorerer vi dette. Vi logger ikke feil. Og dersom statistikk feiler vil vi sende en utbetaling uten å persistere.
Denne PR prøver å løse dette. En TODO i framtiden vil være å gjøre om den withTransaction til å ha et sterkere grensesnitt for å hjelpe på slike feil i fremtiden. withTransaction kan f.eks. ta inn et vararg antall funksjoner som hver må returnere en spesifikk type, f.eks. TransactionFunctionResponse også kan selve withtransaction returnere TransactionReponse. Da slipper vi ha en exception-flyt og det vil bli enklere å skrive tester.

Flytt statistikk ut av transaksjon og logg iverksett-feil

---

web/src/main/kotlin/no/nav/su/se/bakover/web/services/utbetaling/kvittering/UtbetalingKvitteringIbmMqConsumer.kt

For å slippe å boble opp en exception i tilfellene vi ikke ønsker å acke, som da logger stack trace rått til logg. Implementasjonen skal være helt analog til hvordan det var tidligere med auto, bare nå med eksplisitt acking (og fjerning av den implisitte no-ack throwen).
Dokumentasjonen var litt tvetydig, mulig dette kunne vært løst med `AUTO_ACKNOWLEDGE` også, bare ved å unngå å rethrowe. Docen sier noe sånt som at ack skjer automatisk rett etter at `onMessage` returnerer suksessfullt, men det er litt uklart hva dette egentlig betyr og litt kinkig å teste.

Ack kvitteringer fra oppdrag manuelt

---

client/src/main/kotlin/no/nav/su/se/bakover/client/journalpost/JournalpostClientStub.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/journalpost/JournalpostHttpClient.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/journalpost/JournalpostResponse.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/journalpost/JournalpostHttpClientTest.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/journalpost/JournalpostResponseTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/journalpost/FerdigstiltJournalpost.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/journalpost/JournalpostClient.kt
test-common/src/main/kotlin/HenterJournalpostTestData.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/klage/KlageRoutes.kt

Vi rotet litt med begrepene fra dette ble implementert første gang og en liten patch vi gjorde. Så dette er en ganske stor blocker i produkasjon 😬 .
Brukerens klage er et innkommende dokument og ikke et utgående. Da vil også typen endre seg fra FERDIGSTILT til JOURNALFØRT

Bytt fra utgående til innkommende dokument for klages journalpostid

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/Utbetaling.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/UtbetalingTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/brev/BrevServiceImplTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/LagBrevutkastForRevurderingTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RegulerGrunnbeløpServiceImplTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingBeregnOgSimulerTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingIngenEndringTest.kt

Da kan vi gjenbruke logikken dersom vi har sak, uten og måtte gå via databasen. Dette er spesielt med tanke på reguleringsbranchen.

Trekk hentGjeldendeUtbetaling() til Utbetaling.kt

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/avslag/Avslagsgrunn.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/AvslagsBrevInnholdTest.kt

Egentligen skal rekkefølgen i vedtaket være "§§ 3 og 2" men kommer ut som "§§ 2 og 3" fordi vi sortere avslagsparagrafene når vi sender det till pdfgen.
Enkleste løsningen er å fjerne paragraf 2 fordi paragraf 3 er primærparagrafen og paragraf 2 er relevant men ikke nødvendig å ha med i vedtaket.

Fjern paragraf 2 for flyktningsstatus

---

service/src/main/kotlin/no/nav/su/se/bakover/service/statistikk/mappers/BehandlingStatistikkMapper.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/statistikk/BehandlingStatistikkMapperTest.kt

MottattDato beskrives enligt `behandling_schema`:n vi har som: _"Denne datoen forteller fra hvilken dato behandlingen først ble initiert. Datoen brukes i beregning av saksbehandlingstid og skal samsvare med brukerens opplevelse av at saksbehandlingen har startet"_
Tänker att det då burde være den dato som brukern har sendt in klagen enligt saksbehandler.

Endre mottattdato for klage i statistikk

---

database/src/main/kotlin/no/nav/su/se/bakover/database/beregning/PersistertBeregning.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/beregning/PersistertMånedsberegning.kt

-Gjeldende satsfactory er en dyr operasjon, spesielt mtp minne. Opprettelse av denne for hver måned i beregningen gir et unødvendig stort minne-footprint. Opprettet for beregningen som helhet og månedene er det samme, holder dermed å finne gjeldende satsfactory 1 gang.

Unngå å opprett ny satsfactory for hver måned i beregning.

---

database/src/main/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepo.kt
database/src/main/resources/db/migration/V137__legg_til_type_på_sak.sql
domain/src/main/kotlin/no/nav/su/se/bakover/domain/Søknadsinnhold.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/SøknadServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/SøknadTest.kt

* Legger til type-felt på sak i db (alder / uføre - samme som for søknadsinnhold)
* I steden for å hente hele den nye saken når man oppretter en ny sak, så henter vi nå bare to id-er, så slipper vi masse oppslag og mappinger

Legg til type på sak

---

database/src/main/kotlin/no/nav/su/se/bakover/database/klage/klageinstans/KlageinstanshendelsePostgresRepo.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/Sak.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/statistikk/Statistikk.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/statistikk/mappers/StønadsstatistikkMapper.kt
service/src/main/resources/statistikk/stonad_schema.json
service/src/test/kotlin/no/nav/su/se/bakover/service/statistikk/StatistikkSchemaValidatorTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/statistikk/StønadsstatistikkMapperTest.kt
test-common/src/main/kotlin/RevurderingTestData.kt

Det er et ønske fra DVH å rapportere statistikk på EPS sine inntekter.
For å lettest muliggjøre dette legger vi på informasjon om hvem det
tilhører.
(det var opprinnelig et ønske om mange enum-verdier custom mappet men
det er mye stress og det kan de heller fikses slik konsumenter vil
ha det)

Legger inn informasjon om hvem inntekt tilhører

---

service/src/main/kotlin/no/nav/su/se/bakover/service/personhendelser/PersonhendelseService.kt

Er veldig mye støy i loggingen fra personhendelse-consumern. Tenker att det hade varit fint att kun ha det kvar i sikkerloggen hvis en feil skulle uppstå.

Fjern støy i den vanlige loggen, men behold sikkerlog

---

database/src/main/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepo.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepoTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/Sak.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/SakRepo.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/sak/SakService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/sak/SakServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/AccessCheckProxyTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/sak/SakJson.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/sak/SakRoutes.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/sak/SakRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/BeregnRoutesKtTest.kt

Baserer seg på PR'en for å legge til type søknad
Når både uføre- og aldersøknader kan finnes på samme person vil man kunne få flere forskjellige saker for samme person. hentSak for Fnr legger til et ekstra parameter for hvilken type sak man trenger.
Det er nok også nyttig med et endepunkt for å hente alle sakene for et Fnr også, men der er det foreløpig kun laget på repo- / service-nivå.

Legger til håndtering av flere saker i henting av info

---

common/src/main/kotlin/no/nav/su/se/bakover/common/periode/Måned.kt
common/src/main/kotlin/no/nav/su/se/bakover/common/periode/Periode.kt
common/src/test/kotlin/no/nav/su/se/bakover/common/periode/MånedTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/grunnbeløp/GrunnbeløpFactory.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/satser/FullSupplerendeStønadFactory.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/satser/FullSupplerendeStønadForMåned.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/satser/GarantipensjonFactory.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/satser/Knekkpunkt.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/satser/MinsteÅrligYtelseForUføretrygdedeFactory.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/satser/MånedsperiodiserteSatser.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/satser/SatsFactory.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/satser/SatsFactoryForSupplerendeStønad.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/satser/SatsFactoryForSupplerendeStønadPåKnekkpunkt.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vilkår/FormuegrenseForMåned.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vilkår/FormuegrenserFactory.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/grunnbeløp/GrunnbeløpFactoryTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/satser/GarantipensjonFactoryTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/satser/Periode_periodisert_Test.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/satser/SatsFactoryForSupplerendeStønadUføreTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/vilkår/FormuegrenserFactoryTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/grunnlag/FormuevilkårJson.kt

Et forsøk på å krympe inn minneforbruket til satser. Fjernet satser/grunnlag før 2020-01 og etter siste virkningstidspunkt (2022-05).

Fjern futuristiske satser

---

client/src/main/kotlin/no/nav/su/se/bakover/client/pdf/PdfClient.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/VedtakInnholdTestdataBuilder.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/BrevInnhold.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/LagBrevRequest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/Stønadsvedtak.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/visitor/LagBrevRequestVisitor.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/AvslagsBrevInnholdTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/BrevInnholdTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/visitor/LagBrevRequestVisitorTest.kt

For vedtaksbrev og avslagsbrev er disse satt ut fra saksbehandlingen. Når
(om™) vi får aldersbrev implementert for de forskjellige så må pdfclient
gjøre en smartere override og sakstype må settes riktig for de forskjellige
brevene slik at vi kan bruke det i templates i pdfgen.
Eller løse forskjellige brevinnhold for alder og uføre på en annen måte.
Time will tell.

Legger inn sakstype i brevinnhold med default til uføre

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/visitor/LagBrevRequestVisitor.kt
web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/komponenttest/SøknadsbehandlingAlder.kt

Dette er skikkelig hacky, men ble ikke stoppet for å lage brev for alder i lokal testing

Alltid tom liste for uføregrunnlag i vilkårsvurdering for alder

---

.github/workflows/branch-deploy.yml
.github/workflows/branch.yml
.github/workflows/master.yml
.github/workflows/prod-deploy.yml

`docker.pkg.github.com` er deprecated i favør for `ghcr.io`. Jeg har allerede gjort denne endringen i su-pdfgen.

Bytter fra docker.pkg.github.com til ghcr.io

---

web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/sak/SakJsonMatcher.kt
web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/søknadsbehandling/SøknadsbehandlingJsonMatcher.kt
web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/søknadsbehandling/pensjon/LeggTilPensjonsVilkårIT.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/sak/SakJson.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/RevurderingJsonTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/sak/SakJsonTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingJsonTest.kt

Det er en inkosekvens i sakstypene vi dytter til front atm:
* Søknadsinnhold kjører lowercase
* Sak har type-felt i uppercase
Om de burde være upper eller lower er for så vidt ikke riktig, men de burde være like

Lowercase sakstype

---

domain/src/test/kotlin/no/nav/su/se/bakover/domain/vedtak/VedtakPåTidslinjeTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/vedtak/VedtakTest.kt
gradle.properties
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/LagBrevutkastForRevurderingTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RegulerGrunnbeløpServiceImplTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceAttesteringTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceHentTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/vedtak/VedtakServiceImplTest.kt
web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/komponenttest/SøknadsbehandlingAlder.kt
web/build.gradle.kts
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/revurdering/BrevutkastForRevurderingRouteTest.kt

Kan ikke lenger mock'e sealed class / sealed interface virker det som. Kan være fordi det ikke kan kombineres med `open`.

Bump Kotlin from 1.6.2. to 1.7.0

---

client/src/main/kotlin/no/nav/su/se/bakover/client/pdf/PdfClient.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/avslag/Avslagsgrunn.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/BrevInnhold.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vilkår/Vilkårsvurderingsresultat.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/AvslagsBrevInnholdTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/brev/BrevInnholdTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/klage/IverksettAvvistKlageTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/klage/OversendKlageTest.kt

Se PR i su-pdfgen for de nye tekstene. `Avlagsgrunn.PENSJON` er enda ikke fjernet, siden denne er lagret i databasen i dev for noen saker. Siden vi uansett snakket om å slette alderssakene fra dev tenker jeg at det ikke er hensiktsmessig å lage en migrering for dette.

Legger til brev for innvilgelse / avslag alder

---

common/src/main/kotlin/no/nav/su/se/bakover/common/Config.kt
common/src/test/kotlin/no/nav/su/se/bakover/common/ApplicationConfigTest.kt
nais-dev.json
nais-prod.json
web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/SharedRegressionTestData.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/AuthenticationConfig.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/TestEnvironment.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/external/FrikortRoutesKtTest.kt

Åpne opp for `srvfrikorttjenester` mot frikort-routes. `srvfrikortborger` skal fases ut når `srvfrikorttjenester` er oppe og kjører

Åpne opp for en ekstra servicebruker mot frikort

---

database/src/main/kotlin/no/nav/su/se/bakover/database/dokument/DokumentPostgresRepo.kt
database/src/main/resources/db/migration/V158__dokument_generertdokumentjson_fjern_dobbel_serialisering.sql
database/src/test/kotlin/no/nav/su/se/bakover/database/dokument/DokumentPostgresRepoTest.kt
web-regresjonstest/src/test/kotlin/no/nav/su/se/bakover/web/komponenttest/AvslagManglendeDokumentasjonKomponentTest.kt

Denne har blitt lagret i basen som "{\"...\"}" som gjør den vanskelig å gjøre json-spørringer på

Fix genertDokumentJson dobbel serdes

---

database/src/main/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepo.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/søknad/SøknadPostgresRepo.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/søknad/SøknadRepoInternal.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/TestDataHelper.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/Sak.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/Søknad.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknad/SøknadRepo.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadinnhold/ForNav.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadinnhold/Søknadsinnhold.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknad/SøknadTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/søknad/SøknadServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/statistikk/BehandlingStatistikkMapperTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/statistikk/StatistikkServiceImplTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/HentSøknadPdfTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/HentSøknadTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/OpprettManglendeJournalpostOgOppgaveTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/SøknadServiceOgMocks.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/SøknadTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknad/lukk/LukkSøknadServiceImplTest.kt
test-common/src/main/kotlin/GenerelleTestData.kt
test-common/src/main/kotlin/SakTestData.kt
test-common/src/main/kotlin/SøknadTestData.kt
test-common/src/main/kotlin/SøknadsbehandlingTestData.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/drift/FixSøknaderTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/sak/SakRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/UføresøknadJsonTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutesKtTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/beregning/BeregnRoutesKtTest.kt

Usikker på om det hensiktsmessig å bruke `NavIdentBruker` her, eller om det er like greit å bare pakke det ut til en string - retrospektivt heller jeg mot dette. Tanker @hestad ?

Ta vare på innsender av søknad ved første innsending på sak

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/OppdaterRevurderingServiceTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/OppdaterRevurderingsperiodeRoute.kt

Beholder sperren dersom man endrer årsak til REGULER_GRUNNBELØP og det har blitt forhåndsvarslet. Siden vi ikke støtter forhåndsvarsler i denne tilstanden. Dersom det senere blir et krav, må man gjøre litt større endringer.

Fjern oppdater revurdering sperre etter forhåndsvarsel

---

database/src/main/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepo.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/SimulerUtbetalingRequest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/SakRepo.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/Utbetaling.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/StansAvYtelseService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/sak/SakService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/sak/SakServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/StansAvYtelseServiceTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/utbetaling/StansUtbetalingServiceTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingServiceImplTest.kt

La saken opprette utbetalingen som skal simuleres. Med dette unngår at vi oppretter en ny session for å hente sak ved simulering, og åpner for videre refaktorering for å la saken opprette hele stansen.

Unngå nested session ved stans

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/Utbetaling.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/OpphørsperiodeForUtbetalingerTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/RevurderingSimulerTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/visitor/LagBrevRequestVisitorTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/AccessCheckProxy.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/IverksettRevurderingTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/LagBrevutkastForRevurderingTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingBeregnOgSimulerTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/utbetaling/UtbetalingServiceImplTest.kt
test-common/src/main/kotlin/RevurderingTestData.kt
test-common/src/main/kotlin/SimuleringTestData.kt
test-common/src/main/kotlin/persistence/TestDataHelper.kt

Føles som det kan være potensial for videre refaktorering, f.eks trekke ut sjekkene mot tidslinje/tidligere attesteringer fra servicen og inn i domenet. Det vil gi et litt mer behagelig og clean api mot servicen.

Unngå nested session opphør

---

domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/beregning/BeregnRevurderingStrategyDecider.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/LeggTilFradragTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/revurdering/RevurderingServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/revurdering/LeggTilFradragsgrunnlagTest.kt
test-common/src/main/kotlin/RevurderingTestData.kt

Obskur liten detalj som kan føre til at data fra fremtiden "blør tilbake" til revurderinger som gjøres for tidligere perioder men på senere tidspunkt. Erfart case, fradrag for avkorting i fremtidig stønadsperiode ble propagert til en revurdering for en tidligere og helt urelatert periode.

Begrens utplukk fra gjeldende vedtaksdata for beregning til revurderingens periode

---

common/src/main/kotlin/no/nav/su/se/bakover/common/application/MånedBeløp.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/simulering/Simulering.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/simulering/TolketSimulering.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/Sak.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/ValiderOverlappendeStønadsperioder.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/iverksett/KunneIkkeIverksetteSøknadsbehandling.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/iverksett/innvilg/IverksettInnvilgetSøknadsbehandling.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/stønadsperiode/OppdaterStønadsperiode.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/GjeldendeVedtaksdata.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/Stønadsvedtak.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/SakTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/stønadsperiode/OppdaterStønadsperiodeTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceIverksettTest.kt
test-common/src/main/kotlin/TikkendeKlokke.kt
test-common/src/main/kotlin/no/nav/su/se/bakover/test/søknad/SøknadTestData.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/ResultatMappers.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/SøknadsbehandlingRoutes.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/iverksett/IverksettSøknadsbehandlingRoute.kt

Et skritt nærmere parallelle behandlinger. Må gjøre tilsvarende for revurdering og regulering. Vi bør også persistere original saksbehandler+attestants simulerings xml. Bør finne algoritme for å finne ut om et opphør tidligere har vært utbetalt for å sperre de tilfellene.

Oppdater og iverksett søknadsbehandling - valider overlappende stønadsperioder

---

client/src/main/kotlin/no/nav/su/se/bakover/client/person/MicrosoftGraphApiClient.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/person/MicrosoftGraphApiClientTest.kt

Gjør kallet litt mer robust, siden ikke alle brukere har mail-feltet vi bytter ut. Se https://nav-it.slack.com/archives/C0190RZ6HB4/p1671536757273469 og https://github.com/navikt/kabal-innstillinger/blob/main/src/main/kotlin/no/nav/klage/oppgave/clients/azure/MicrosoftGraphClient.kt og https://learn.microsoft.com/en-us/answers/questions/577870/filtering-on-onpremisessamaccountname-is-not-worki

Bytt ut microsoftGraphFilter med onPremisesSamAccountName

---

client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/avstemming/AvstemmingPublisherTest.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/avstemming/GrensesnittavstemmingDataBuilderTest.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/avstemming/GrunnlagBuilderTest.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/simulering/SimuleringRequestBuilderTest.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/simulering/SimuleringRequestBuilderValidationTest.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/utbetaling/UtbetalingRequestTest.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/oppdrag/utbetaling/UtbetalingXmlMappingTest.kt
common/src/main/kotlin/no/nav/su/se/bakover/common/Rekkefølge.kt
common/src/test/kotlin/no/nav/su/se/bakover/common/RekkefølgeTest.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/utbetaling/UtbetalingRepoInternal.kt
database/src/main/resources/db/migration/V179__utbetalingslinje_legg_til_rekkefølge.sql
database/src/test/kotlin/no/nav/su/se/bakover/database/utbetaling/UtbetalingMapperTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/Utbetaling.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/Utbetalingshistorikk.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/Utbetalingslinje.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppdrag/Utbetalingsstrategi.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/UtbetalingTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/UtbetalingslinjeTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/avstemming/KonsistensavstemmingTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/utbetaling/UtbetalingsstrategiGjenopptaTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/utbetaling/UtbetalingsstrategiNyTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/utbetaling/UtbetalingsstrategiOpphørTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/oppdrag/utbetaling/UtbetalingsstrategiStansTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/VurderOmBeløpsendringErStørreEnnEllerLik10ProsentAvGjeldendeUtbetalingTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/tidslinje/TidslinjeForUtbetalingerTest.kt
test-common/src/main/kotlin/UtbetalingTestData.kt
test-common/src/main/kotlin/persistence/TestDataHelper.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/routes/sak/SakJsonTest.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/services/utbetaling/kvittering/LokalKvitteringJobTest.kt

Første steg i å fjerne opprettet fra utbetalingslinja (evt. la den være lik som opprettet på utbetaling). Trenger dette før vi gjør opprettet migreringen.

Legg til rekkefølge på utbetalingstidslinje

---

database/src/main/kotlin/no/nav/su/se/bakover/database/sak/SakPostgresRepo.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/vedtak/VedtakPostgresRepo.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/vedtak/VedtakPostgresRepoTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/Sak.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/sak/SakRepo.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/Avslagsvedtak.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/VedtakInnvilgetSøknadsbehandling.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/VedtakIverksattSøknadsbehandling.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/VedtakRepo.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/statistikk/ResendStatistikkhendelserService.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/statistikk/ResendStatistikkhendelserServiceImpl.kt
statistikk/src/main/kotlin/no/nav/su/se/bakover/statistikk/stønad/StønadsstatistikkMapper.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/Routes.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/drift/DriftRoutes.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/drift/ResendStatistikkRoute.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/services/AccessCheckProxy.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/services/ServiceBuilder.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/services/Services.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/TestServicesBuilder.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/services/AccessCheckProxyTest.kt

IverksettSøknadsbehandlingServiceImpl som ble trukket ut fra SøknadsbehandlingServiceImpl i oktober har aldri sendt statistikk. Legger til en jobb som igangsettes fra driftssiden som kan rekjøre disse fra en dato.

Legg til endepunkt for å resende søknadsbehandlingsvedtak

---

common/infrastructure/src/main/kotlin/no/nav/su/se/bakover/common/infrastructure/web/Feilresponser.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Attestering.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/LagBrevRequest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/PdfInnhold.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/AvvistKlage.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/IverksattAvvistKlage.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/Klage.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/KlageTilAttestering.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/OversendtKlage.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/VurdertKlage.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/klage/KlageServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/klage/HentBrevutkastTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/klage/OversendKlageTest.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/klage/KlageRoutes.kt

Send attestant-navnet til oversendelses brevet (fikset at saksbehandler også vises i PDF-gen)

Attestantnavn oversendelse

---

client/src/main/kotlin/no/nav/su/se/bakover/client/skatteetaten/SpesifisertSummertSkattegrunnlagResponseJson.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/skatteetaten/SkatteClientTest.kt

jeg var veldig usikker hvordan vi egentlig har lyst til å håndtere at grunnlag er null. Nå skal det i det minste funke

fikser deserialisering av Skattegrunnlagsobjekt dersom den er null

---

client/src/main/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveHttpClient.kt
client/src/main/kotlin/no/nav/su/se/bakover/client/oppgave/OppgavebeskrivelseMapper.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/oppgave/OppgavebeskrivelseMapperTest.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/personhendelse/PersonhendelsePostgresRepo.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/personhendelse/PersonhendelsePostgresRepoTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppgave/OppgaveConfig.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/personhendelse/Personhendelse.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/personhendelse/PersonhendelseRepo.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/Vedtaksammendrag.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/personhendelser/PersonhendelseService.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/personhendelser/PersonhendelseServiceTest.kt
test-common/src/main/kotlin/PersonhendelseTestData.kt

Tidligere laget vi en oppgave per personhendelse, men nå grupperer vi hendelsene per sak og legger de i samme oppgaven. Neste steg blir å hente tidligere åpne oppgaver og legge de der istedet.

Grupper personhendelseoppgaver på sakId

---

common/domain/src/main/kotlin/no/nav/su/se/bakover/common/domain/Stønadsperiode.kt
common/domain/src/main/kotlin/no/nav/su/se/bakover/common/domain/tid/periode/DatoIntervall.kt
common/domain/src/main/kotlin/no/nav/su/se/bakover/common/domain/tid/periode/Måned.kt
common/domain/src/main/kotlin/no/nav/su/se/bakover/common/domain/tid/periode/Periode.kt
common/domain/src/test/kotlin/no/nav/su/se/bakover/common/domain/periode/DatoIntervallTest.kt
common/domain/src/test/kotlin/no/nav/su/se/bakover/common/domain/periode/DatoIntervall_dagerTest.kt
common/domain/src/test/kotlin/no/nav/su/se/bakover/common/domain/periode/DatoIntervall_slåSammenTest.kt
common/domain/src/test/kotlin/no/nav/su/se/bakover/common/domain/periode/MånedTest.kt
tilbakekreving/domain/src/main/kotlin/tilbakekreving/domain/kravgrunnlag/Kravgrunnlag.kt
tilbakekreving/domain/src/main/kotlin/tilbakekreving/domain/vurdering/Vurderinger.kt
tilbakekreving/domain/src/main/kotlin/tilbakekreving/domain/vurdering/VurderingerMedKrav.kt

Det gir ikke mening og la en liste med DatoIntervall (som kan ha overlapp) være sorterbar.
Dette gjelder også Periode og Stønadsperiode, som må fikses senere.

fjern comparable for datointervall

---

client/src/main/kotlin/no/nav/su/se/bakover/client/oppgave/OppgavebeskrivelseMapper.kt
client/src/test/kotlin/no/nav/su/se/bakover/client/oppgave/OppgaveHttpClientTest.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/klage/klageinstans/KlageinstanshendelsePostgresRepo.kt
database/src/main/kotlin/no/nav/su/se/bakover/database/klage/klageinstans/VedtattUtfallJson.kt
database/src/main/resources/db/migration/V209__klageinstanshendelse_utlest_mottattKlageinstans.sql
database/src/test/kotlin/no/nav/su/se/bakover/database/klage/KlagePostgresRepoTest.kt
database/src/test/kotlin/no/nav/su/se/bakover/database/klage/KlageinstanshendelsePostgresRepoTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/Klageinstansvedtak.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/klage/OversendtKlage.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/oppgave/OppgaveConfig.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/klage/KlageinstanshendelseServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/klage/KlageinstanshendelseServiceImplTest.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/klage/VilkårsvurderKlageTest.kt
test-common/src/main/kotlin/persistence/TestDataHelper.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/routes/klage/KlageJson.kt
web/src/main/kotlin/no/nav/su/se/bakover/web/services/klage/klageinstans/KlageinstanshendelseDto.kt
web/src/test/kotlin/no/nav/su/se/bakover/web/services/klage/klageinstans/KlageinstanshendelseDtoTest.kt

utfall mot frontend har nå blitt nullable i de tilfellene det ikke er en KlagebehandlingAvsluttet

Støtt klageinstanshendelse AnkebehandlingOpprettet

---

behandling/revurdering/domain/build.gradle.kts
behandling/revurdering/domain/src/main/kotlin/behandling/revurdering/domain/Opphørsgrunn.kt
behandling/revurdering/domain/src/test/kotlin/vilkår/common/domain/OpphørsgrunnTest.kt
beregning/src/main/kotlin/beregning/domain/Beregningsgrunnlag.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/jsonRequest/OpphørsvedtakPdfInnhold.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/opphør/IdentifiserRevurderingsopphørSomIkkeStøttes.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/opphør/VurderOpphørVedRevurdering.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/beregning/BeregningsgrunnlagTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/opphør/IdentifiserRevurderingsopphørSomIkkeStøttesKombiopphørTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/opphør/IdentifiserRevurderingsopphørSomIkkeStøttesTest.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/revurdering/opphør/VurderOpphørVedRevurderingTest.kt
test-common/src/main/kotlin/BeregningTestData.kt
test-common/src/main/kotlin/GrunnlagsdataTestData.kt
test-common/src/main/kotlin/RevurderingTestData.kt
test-common/src/main/kotlin/vilkår/UførevilkårTestData.kt

Legger til støtte for å opphøre en periode som har kombinasjon av opphørsgunnene: SU_UNDER_MINSTEGRENSE (2%) og FOR_HØY_INNTEKT (0%)
Sjekk samhendlingskanal på teams angående dette: https://teams.microsoft.com/l/message/19:jjE41BT-ZVDOi_UVyZsfeS6IT-ytXAFxFoGIkbBqatQ1@thread.skype/1725528028308

Aksepter kombinasjon av 0% og under 2% inntektsopphør

---

bootstrap/src/test/kotlin/no/nav/su/se/bakover/domain/brev/command/PåminnelseNyStønadsperiodeDokumentCommandTest.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/command/PåminnelseNyStønadsperiodeDokumentCommand.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/brev/jsonRequest/PåminnelseNyStønadsperiodePdfInnhold.kt
domain/src/main/kotlin/no/nav/su/se/bakover/domain/jobcontext/SendPåminnelseNyStønadsperiodeContext.kt
domain/src/test/kotlin/no/nav/su/se/bakover/domain/jobcontext/SendPåminnelseNyStønadsperiodeContextTest.kt
service/src/main/kotlin/no/nav/su/se/bakover/service/SendPåminnelserOmNyStønadsperiodeServiceImpl.kt
service/src/test/kotlin/no/nav/su/se/bakover/service/SendPåminnelserOmNyStønadsperiodeServiceImplTest.kt

Legger til felt uføreSomFyller67 på PåminnelseNyStønadsperiodeDokumentCommand for å kunne vise riktig i brev.
Fjerner også felt "halvtGrunnbeløp" fordi det ikke brukes i brevet.

Nytt felt for om uføre sak fyller 67

---

.nais/dev.yaml
.nais/prod.yaml

* Fra saf-scope til dokdistfordeling-scope for dokdistfordeling integrasjonen
> Vi gjør endringer på autentisering i dokdistfordeling, for å sørge for at autentisering med EntraID er implementert som tiltenkt. Pr i dag kalles distribuerJournalpost med EntraID tokens scopet mot SAF, hvor dokdistfordeling proxyer dette tokenet videre i kall til SAF. Vi ønsker på sikt å endre dette til av dokdistfordeling kun kan kalles med tokens som er scopet mot seg selv. Steg 1 av denne endringen innføres nå, hvor dokdistfordeling i en overgangsperiode vil akseptere tokens med enten saf- eller dokdistfordeling-scope. Dette innebærer at konsumenter ikke trenger å gjøre noe umiddelbart, men på sikt (helst så snart som mulig) må endre scope for tokenet de kaller dokdistfordeling med. Vi kommer til å bistå …

Oppdaterer scope for dokdistfordeling
